//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAsyncAsyncSession")
#ifdef RESTRICT_OrgGreenrobotGreendaoAsyncAsyncSession
#define INCLUDE_ALL_OrgGreenrobotGreendaoAsyncAsyncSession 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoAsyncAsyncSession 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoAsyncAsyncSession

#if !defined (OrgGreenrobotGreendaoAsyncAsyncSession_) && (INCLUDE_ALL_OrgGreenrobotGreendaoAsyncAsyncSession || defined(INCLUDE_OrgGreenrobotGreendaoAsyncAsyncSession))
#define OrgGreenrobotGreendaoAsyncAsyncSession_

@class IOSClass;
@class IOSObjectArray;
@class OrgGreenrobotGreendaoAbstractDaoSession;
@class OrgGreenrobotGreendaoAsyncAsyncOperation;
@class OrgGreenrobotGreendaoQueryQuery;
@protocol JavaLangIterable;
@protocol JavaLangRunnable;
@protocol JavaUtilConcurrentCallable;
@protocol OrgGreenrobotGreendaoAsyncAsyncOperationListener;

@interface OrgGreenrobotGreendaoAsyncAsyncSession : NSObject

#pragma mark Public

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDaoSession:(OrgGreenrobotGreendaoAbstractDaoSession *)daoSession;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)callInTxWithJavaUtilConcurrentCallable:(id<JavaUtilConcurrentCallable>)callable;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)callInTxWithJavaUtilConcurrentCallable:(id<JavaUtilConcurrentCallable>)callable
                                                                             withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)countWithIOSClass:(IOSClass *)entityClass;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)countWithIOSClass:(IOSClass *)entityClass
                                                        withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)delete__WithId:(id)entity;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)delete__WithId:(id)entity
                                                     withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteAllWithIOSClass:(IOSClass *)entityClass;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteAllWithIOSClass:(IOSClass *)entityClass
                                                            withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteByKeyWithId:(id)key;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteByKeyWithId:(id)key
                                                        withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteInTxWithIOSClass:(IOSClass *)entityClass
                                                   withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteInTxWithIOSClass:(IOSClass *)entityClass
                                                             withInt:(jint)flags
                                                   withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteInTxWithIOSClass:(IOSClass *)entityClass
                                                withJavaLangIterable:(id<JavaLangIterable>)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)deleteInTxWithIOSClass:(IOSClass *)entityClass
                                                withJavaLangIterable:(id<JavaLangIterable>)entities
                                                             withInt:(jint)flags;

- (id<OrgGreenrobotGreendaoAsyncAsyncOperationListener>)getListener;

- (id<OrgGreenrobotGreendaoAsyncAsyncOperationListener>)getListenerMainThread;

- (jint)getMaxOperationCountToMerge;

- (jint)getSessionFlags;

- (jint)getWaitForMergeMillis;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertWithId:(id)entity;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertWithId:(id)entity
                                                   withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertInTxWithIOSClass:(IOSClass *)entityClass
                                                   withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertInTxWithIOSClass:(IOSClass *)entityClass
                                                             withInt:(jint)flags
                                                   withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertInTxWithIOSClass:(IOSClass *)entityClass
                                                withJavaLangIterable:(id<JavaLangIterable>)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertInTxWithIOSClass:(IOSClass *)entityClass
                                                withJavaLangIterable:(id<JavaLangIterable>)entities
                                                             withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertOrReplaceWithId:(id)entity;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertOrReplaceWithId:(id)entity
                                                            withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertOrReplaceInTxWithIOSClass:(IOSClass *)entityClass
                                                            withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertOrReplaceInTxWithIOSClass:(IOSClass *)entityClass
                                                                      withInt:(jint)flags
                                                            withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertOrReplaceInTxWithIOSClass:(IOSClass *)entityClass
                                                         withJavaLangIterable:(id<JavaLangIterable>)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)insertOrReplaceInTxWithIOSClass:(IOSClass *)entityClass
                                                         withJavaLangIterable:(id<JavaLangIterable>)entities
                                                                      withInt:(jint)flags;

- (jboolean)isCompleted;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)load__WithIOSClass:(IOSClass *)entityClass
                                                          withId:(id)key;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)load__WithIOSClass:(IOSClass *)entityClass
                                                          withId:(id)key
                                                         withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)loadAllWithIOSClass:(IOSClass *)entityClass;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)loadAllWithIOSClass:(IOSClass *)entityClass
                                                          withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)queryListWithOrgGreenrobotGreendaoQueryQuery:(OrgGreenrobotGreendaoQueryQuery *)query;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)queryListWithOrgGreenrobotGreendaoQueryQuery:(OrgGreenrobotGreendaoQueryQuery *)query
                                                                                   withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)queryUniqueWithOrgGreenrobotGreendaoQueryQuery:(OrgGreenrobotGreendaoQueryQuery *)query;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)queryUniqueWithOrgGreenrobotGreendaoQueryQuery:(OrgGreenrobotGreendaoQueryQuery *)query
                                                                                     withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)refreshWithId:(id)entity;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)refreshWithId:(id)entity
                                                    withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)runInTxWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)runInTxWithJavaLangRunnable:(id<JavaLangRunnable>)runnable
                                                                  withInt:(jint)flags;

- (void)setListenerWithOrgGreenrobotGreendaoAsyncAsyncOperationListener:(id<OrgGreenrobotGreendaoAsyncAsyncOperationListener>)listener;

- (void)setListenerMainThreadWithOrgGreenrobotGreendaoAsyncAsyncOperationListener:(id<OrgGreenrobotGreendaoAsyncAsyncOperationListener>)listenerMainThread;

- (void)setMaxOperationCountToMergeWithInt:(jint)maxOperationCountToMerge;

- (void)setSessionFlagsWithInt:(jint)sessionFlags;

- (void)setWaitForMergeMillisWithInt:(jint)waitForMergeMillis;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)updateWithId:(id)entity;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)updateWithId:(id)entity
                                                   withInt:(jint)flags;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)updateInTxWithIOSClass:(IOSClass *)entityClass
                                                   withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)updateInTxWithIOSClass:(IOSClass *)entityClass
                                                             withInt:(jint)flags
                                                   withNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)updateInTxWithIOSClass:(IOSClass *)entityClass
                                                withJavaLangIterable:(id<JavaLangIterable>)entities;

- (OrgGreenrobotGreendaoAsyncAsyncOperation *)updateInTxWithIOSClass:(IOSClass *)entityClass
                                                withJavaLangIterable:(id<JavaLangIterable>)entities
                                                             withInt:(jint)flags;

- (void)waitForCompletion;

- (jboolean)waitForCompletionWithInt:(jint)maxMillis;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoAsyncAsyncSession)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoAsyncAsyncSession_initWithOrgGreenrobotGreendaoAbstractDaoSession_(OrgGreenrobotGreendaoAsyncAsyncSession *self, OrgGreenrobotGreendaoAbstractDaoSession *daoSession);

FOUNDATION_EXPORT OrgGreenrobotGreendaoAsyncAsyncSession *new_OrgGreenrobotGreendaoAsyncAsyncSession_initWithOrgGreenrobotGreendaoAbstractDaoSession_(OrgGreenrobotGreendaoAbstractDaoSession *daoSession) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoAsyncAsyncSession *create_OrgGreenrobotGreendaoAsyncAsyncSession_initWithOrgGreenrobotGreendaoAbstractDaoSession_(OrgGreenrobotGreendaoAbstractDaoSession *daoSession);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoAsyncAsyncSession)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAsyncAsyncSession")
