//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoInternalUnitTestDaoAccess")
#ifdef RESTRICT_OrgGreenrobotGreendaoInternalUnitTestDaoAccess
#define INCLUDE_ALL_OrgGreenrobotGreendaoInternalUnitTestDaoAccess 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoInternalUnitTestDaoAccess 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoInternalUnitTestDaoAccess

#if !defined (OrgGreenrobotGreendaoInternalUnitTestDaoAccess_) && (INCLUDE_ALL_OrgGreenrobotGreendaoInternalUnitTestDaoAccess || defined(INCLUDE_OrgGreenrobotGreendaoInternalUnitTestDaoAccess))
#define OrgGreenrobotGreendaoInternalUnitTestDaoAccess_

@class IOSClass;
@class IOSObjectArray;
@class OrgGreenrobotGreendaoAbstractDao;
@protocol AndroidDatabaseCursor;
@protocol OrgGreenrobotGreendaoDatabaseDatabase;
@protocol OrgGreenrobotGreendaoIdentityscopeIdentityScope;

@interface OrgGreenrobotGreendaoInternalUnitTestDaoAccess : NSObject

#pragma mark Public

- (instancetype)initWithOrgGreenrobotGreendaoDatabaseDatabase:(id<OrgGreenrobotGreendaoDatabaseDatabase>)db
                                                 withIOSClass:(IOSClass *)daoClass
          withOrgGreenrobotGreendaoIdentityscopeIdentityScope:(id<OrgGreenrobotGreendaoIdentityscopeIdentityScope>)identityScope;

- (OrgGreenrobotGreendaoAbstractDao *)getDao;

- (id)getKeyWithId:(id)entity;

- (IOSObjectArray *)getProperties;

- (jboolean)isEntityUpdateable;

- (id)readEntityWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)cursor
                                  withInt:(jint)offset;

- (id)readKeyWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)cursor
                               withInt:(jint)offset;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoInternalUnitTestDaoAccess)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoInternalUnitTestDaoAccess_initWithOrgGreenrobotGreendaoDatabaseDatabase_withIOSClass_withOrgGreenrobotGreendaoIdentityscopeIdentityScope_(OrgGreenrobotGreendaoInternalUnitTestDaoAccess *self, id<OrgGreenrobotGreendaoDatabaseDatabase> db, IOSClass *daoClass, id<OrgGreenrobotGreendaoIdentityscopeIdentityScope> identityScope);

FOUNDATION_EXPORT OrgGreenrobotGreendaoInternalUnitTestDaoAccess *new_OrgGreenrobotGreendaoInternalUnitTestDaoAccess_initWithOrgGreenrobotGreendaoDatabaseDatabase_withIOSClass_withOrgGreenrobotGreendaoIdentityscopeIdentityScope_(id<OrgGreenrobotGreendaoDatabaseDatabase> db, IOSClass *daoClass, id<OrgGreenrobotGreendaoIdentityscopeIdentityScope> identityScope) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoInternalUnitTestDaoAccess *create_OrgGreenrobotGreendaoInternalUnitTestDaoAccess_initWithOrgGreenrobotGreendaoDatabaseDatabase_withIOSClass_withOrgGreenrobotGreendaoIdentityscopeIdentityScope_(id<OrgGreenrobotGreendaoDatabaseDatabase> db, IOSClass *daoClass, id<OrgGreenrobotGreendaoIdentityscopeIdentityScope> identityScope);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoInternalUnitTestDaoAccess)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoInternalUnitTestDaoAccess")
