//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidDatabaseCursor.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OrgGreenrobotGreendaoAbstractDao.h"
#include "OrgGreenrobotGreendaoDaoException.h"
#include "OrgGreenrobotGreendaoDatabaseDatabase.h"
#include "OrgGreenrobotGreendaoQueryAbstractQuery.h"
#include "OrgGreenrobotGreendaoQueryAbstractQueryData.h"
#include "OrgGreenrobotGreendaoQueryCountQuery.h"
#include "java/lang/Boolean.h"
#include "java/util/Date.h"

@class OrgGreenrobotGreendaoQueryCountQuery_QueryData;

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface OrgGreenrobotGreendaoQueryCountQuery () {
 @public
  OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData_;
}

- (instancetype)initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData:(OrgGreenrobotGreendaoQueryCountQuery_QueryData *)queryData
                                  withOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                                          withNSString:(NSString *)sql
                                                     withNSStringArray:(IOSObjectArray *)initialValues;

@end

J2OBJC_FIELD_SETTER(OrgGreenrobotGreendaoQueryCountQuery, queryData_, OrgGreenrobotGreendaoQueryCountQuery_QueryData *)

__attribute__((unused)) static void OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery *self, OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues);

__attribute__((unused)) static OrgGreenrobotGreendaoQueryCountQuery *new_OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgGreenrobotGreendaoQueryCountQuery *create_OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues);

@interface OrgGreenrobotGreendaoQueryCountQuery_QueryData : OrgGreenrobotGreendaoQueryAbstractQueryData

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                            withNSString:(NSString *)sql
                                       withNSStringArray:(IOSObjectArray *)initialValues;

- (OrgGreenrobotGreendaoQueryCountQuery *)createQuery;

- (OrgGreenrobotGreendaoQueryCountQuery *)forCurrentThreadWithOrgGreenrobotGreendaoQueryAbstractQuery:(OrgGreenrobotGreendaoQueryCountQuery *)arg0;

- (OrgGreenrobotGreendaoQueryCountQuery *)forCurrentThread;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoQueryCountQuery_QueryData)

__attribute__((unused)) static void OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery_QueryData *self, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues);

__attribute__((unused)) static OrgGreenrobotGreendaoQueryCountQuery_QueryData *new_OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgGreenrobotGreendaoQueryCountQuery_QueryData *create_OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoQueryCountQuery_QueryData)

@implementation OrgGreenrobotGreendaoQueryCountQuery

+ (OrgGreenrobotGreendaoQueryCountQuery *)createWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                                                        withNSString:(NSString *)sql
                                                                   withNSObjectArray:(IOSObjectArray *)initialValues {
  return OrgGreenrobotGreendaoQueryCountQuery_createWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSObjectArray_(dao, sql, initialValues);
}

- (instancetype)initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData:(OrgGreenrobotGreendaoQueryCountQuery_QueryData *)queryData
                                  withOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                                          withNSString:(NSString *)sql
                                                     withNSStringArray:(IOSObjectArray *)initialValues {
  OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(self, queryData, dao, sql, initialValues);
  return self;
}

- (OrgGreenrobotGreendaoQueryCountQuery *)forCurrentThread {
  return ((OrgGreenrobotGreendaoQueryCountQuery *) [((OrgGreenrobotGreendaoQueryCountQuery_QueryData *) nil_chk(queryData_)) forCurrentThreadWithOrgGreenrobotGreendaoQueryAbstractQuery:self]);
}

- (jlong)count {
  [self checkThread];
  id<AndroidDatabaseCursor> cursor = [((id<OrgGreenrobotGreendaoDatabaseDatabase>) nil_chk([((OrgGreenrobotGreendaoAbstractDao *) nil_chk(dao_)) getDatabase])) rawQueryWithNSString:sql_ withNSStringArray:parameters_];
  @try {
    if (![((id<AndroidDatabaseCursor>) nil_chk(cursor)) moveToNext]) {
      @throw create_OrgGreenrobotGreendaoDaoException_initWithNSString_(@"No result for count");
    }
    else if (![cursor isLast]) {
      @throw create_OrgGreenrobotGreendaoDaoException_initWithNSString_(JreStrcat("$I", @"Unexpected row count: ", [cursor getCount]));
    }
    else if ([cursor getColumnCount] != 1) {
      @throw create_OrgGreenrobotGreendaoDaoException_initWithNSString_(JreStrcat("$I", @"Unexpected column count: ", [cursor getColumnCount]));
    }
    return [cursor getLongWithInt:0];
  }
  @finally {
    [cursor close];
  }
}

- (OrgGreenrobotGreendaoQueryCountQuery *)setParameterWithInt:(jint)index
                                                       withId:(id)parameter {
  return (OrgGreenrobotGreendaoQueryCountQuery *) cast_chk([super setParameterWithInt:index withId:parameter], [OrgGreenrobotGreendaoQueryCountQuery class]);
}

- (OrgGreenrobotGreendaoQueryCountQuery *)setParameterWithInt:(jint)index
                                             withJavaUtilDate:(JavaUtilDate *)parameter {
  return (OrgGreenrobotGreendaoQueryCountQuery *) cast_chk([super setParameterWithInt:index withJavaUtilDate:parameter], [OrgGreenrobotGreendaoQueryCountQuery class]);
}

- (OrgGreenrobotGreendaoQueryCountQuery *)setParameterWithInt:(jint)index
                                          withJavaLangBoolean:(JavaLangBoolean *)parameter {
  return (OrgGreenrobotGreendaoQueryCountQuery *) cast_chk([super setParameterWithInt:index withJavaLangBoolean:parameter], [OrgGreenrobotGreendaoQueryCountQuery class]);
}

- (void)dealloc {
  RELEASE_(queryData_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgGreenrobotGreendaoQueryCountQuery;", 0x8, 0, 1, -1, 2, -1, -1 },
    { NULL, NULL, 0x2, -1, 3, -1, 4, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryCountQuery;", 0x1, -1, -1, -1, 5, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryCountQuery;", 0x1, 6, 7, -1, 8, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryCountQuery;", 0x1, 6, 9, -1, 10, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryCountQuery;", 0x1, 6, 11, -1, 12, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(createWithOrgGreenrobotGreendaoAbstractDao:withNSString:withNSObjectArray:);
  methods[1].selector = @selector(initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData:withOrgGreenrobotGreendaoAbstractDao:withNSString:withNSStringArray:);
  methods[2].selector = @selector(forCurrentThread);
  methods[3].selector = @selector(count);
  methods[4].selector = @selector(setParameterWithInt:withId:);
  methods[5].selector = @selector(setParameterWithInt:withJavaUtilDate:);
  methods[6].selector = @selector(setParameterWithInt:withJavaLangBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "queryData_", "LOrgGreenrobotGreendaoQueryCountQuery_QueryData;", .constantValue.asLong = 0, 0x12, -1, -1, 13, -1 },
  };
  static const void *ptrTable[] = { "create", "LOrgGreenrobotGreendaoAbstractDao;LNSString;[LNSObject;", "<T2:Ljava/lang/Object;>(Lorg/greenrobot/greendao/AbstractDao<TT2;*>;Ljava/lang/String;[Ljava/lang/Object;)Lorg/greenrobot/greendao/query/CountQuery<TT2;>;", "LOrgGreenrobotGreendaoQueryCountQuery_QueryData;LOrgGreenrobotGreendaoAbstractDao;LNSString;[LNSString;", "(Lorg/greenrobot/greendao/query/CountQuery$QueryData<TT;>;Lorg/greenrobot/greendao/AbstractDao<TT;*>;Ljava/lang/String;[Ljava/lang/String;)V", "()Lorg/greenrobot/greendao/query/CountQuery<TT;>;", "setParameter", "ILNSObject;", "(ILjava/lang/Object;)Lorg/greenrobot/greendao/query/CountQuery<TT;>;", "ILJavaUtilDate;", "(ILjava/util/Date;)Lorg/greenrobot/greendao/query/CountQuery<TT;>;", "ILJavaLangBoolean;", "(ILjava/lang/Boolean;)Lorg/greenrobot/greendao/query/CountQuery<TT;>;", "Lorg/greenrobot/greendao/query/CountQuery$QueryData<TT;>;", "LOrgGreenrobotGreendaoQueryCountQuery_QueryData;", "<T:Ljava/lang/Object;>Lorg/greenrobot/greendao/query/AbstractQuery<TT;>;" };
  static const J2ObjcClassInfo _OrgGreenrobotGreendaoQueryCountQuery = { "CountQuery", "org.greenrobot.greendao.query", ptrTable, methods, fields, 7, 0x1, 7, 1, -1, 14, -1, 15, -1 };
  return &_OrgGreenrobotGreendaoQueryCountQuery;
}

@end

OrgGreenrobotGreendaoQueryCountQuery *OrgGreenrobotGreendaoQueryCountQuery_createWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSObjectArray_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) {
  OrgGreenrobotGreendaoQueryCountQuery_initialize();
  OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData = create_OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(dao, sql, OrgGreenrobotGreendaoQueryAbstractQuery_toStringArrayWithNSObjectArray_(initialValues));
  return [queryData forCurrentThread];
}

void OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery *self, OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) {
  OrgGreenrobotGreendaoQueryAbstractQuery_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(self, dao, sql, initialValues);
  JreStrongAssign(&self->queryData_, queryData);
}

OrgGreenrobotGreendaoQueryCountQuery *new_OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) {
  J2OBJC_NEW_IMPL(OrgGreenrobotGreendaoQueryCountQuery, initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_, queryData, dao, sql, initialValues)
}

OrgGreenrobotGreendaoQueryCountQuery *create_OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery_QueryData *queryData, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) {
  J2OBJC_CREATE_IMPL(OrgGreenrobotGreendaoQueryCountQuery, initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_, queryData, dao, sql, initialValues)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGreenrobotGreendaoQueryCountQuery)

@implementation OrgGreenrobotGreendaoQueryCountQuery_QueryData

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                            withNSString:(NSString *)sql
                                       withNSStringArray:(IOSObjectArray *)initialValues {
  OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(self, dao, sql, initialValues);
  return self;
}

- (OrgGreenrobotGreendaoQueryCountQuery *)createQuery {
  return create_OrgGreenrobotGreendaoQueryCountQuery_initWithOrgGreenrobotGreendaoQueryCountQuery_QueryData_withOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(self, dao_, sql_, [((IOSObjectArray *) nil_chk(initialValues_)) java_clone]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, 1, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryCountQuery;", 0x4, -1, -1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgGreenrobotGreendaoAbstractDao:withNSString:withNSStringArray:);
  methods[1].selector = @selector(createQuery);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LOrgGreenrobotGreendaoAbstractDao;LNSString;[LNSString;", "(Lorg/greenrobot/greendao/AbstractDao<TT2;*>;Ljava/lang/String;[Ljava/lang/String;)V", "()Lorg/greenrobot/greendao/query/CountQuery<TT2;>;", "LOrgGreenrobotGreendaoQueryCountQuery;", "<T2:Ljava/lang/Object;>Lorg/greenrobot/greendao/query/AbstractQueryData<TT2;Lorg/greenrobot/greendao/query/CountQuery<TT2;>;>;" };
  static const J2ObjcClassInfo _OrgGreenrobotGreendaoQueryCountQuery_QueryData = { "QueryData", "org.greenrobot.greendao.query", ptrTable, methods, NULL, 7, 0x1a, 2, 0, 3, -1, -1, 4, -1 };
  return &_OrgGreenrobotGreendaoQueryCountQuery_QueryData;
}

@end

void OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryCountQuery_QueryData *self, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) {
  OrgGreenrobotGreendaoQueryAbstractQueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(self, dao, sql, initialValues);
}

OrgGreenrobotGreendaoQueryCountQuery_QueryData *new_OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) {
  J2OBJC_NEW_IMPL(OrgGreenrobotGreendaoQueryCountQuery_QueryData, initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_, dao, sql, initialValues)
}

OrgGreenrobotGreendaoQueryCountQuery_QueryData *create_OrgGreenrobotGreendaoQueryCountQuery_QueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues) {
  J2OBJC_CREATE_IMPL(OrgGreenrobotGreendaoQueryCountQuery_QueryData, initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_, dao, sql, initialValues)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGreenrobotGreendaoQueryCountQuery_QueryData)
