//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoRxRxDao")
#ifdef RESTRICT_OrgGreenrobotGreendaoRxRxDao
#define INCLUDE_ALL_OrgGreenrobotGreendaoRxRxDao 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoRxRxDao 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoRxRxDao

#if !defined (OrgGreenrobotGreendaoRxRxDao_) && (INCLUDE_ALL_OrgGreenrobotGreendaoRxRxDao || defined(INCLUDE_OrgGreenrobotGreendaoRxRxDao))
#define OrgGreenrobotGreendaoRxRxDao_

#define RESTRICT_OrgGreenrobotGreendaoRxRxBase 1
#define INCLUDE_OrgGreenrobotGreendaoRxRxBase 1
#include "OrgGreenrobotGreendaoRxRxBase.h"

@class IOSObjectArray;
@class OrgGreenrobotGreendaoAbstractDao;
@class RxObservable;
@class RxScheduler;
@protocol JavaLangIterable;

@interface OrgGreenrobotGreendaoRxRxDao : OrgGreenrobotGreendaoRxRxBase

#pragma mark Public

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao;

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                         withRxScheduler:(RxScheduler *)scheduler;

- (RxObservable *)count;

- (RxObservable *)delete__WithId:(id)entity;

- (RxObservable *)deleteAll;

- (RxObservable *)deleteByKeyWithId:(id)key;

- (RxObservable *)deleteByKeyInTxWithJavaLangIterable:(id<JavaLangIterable>)keys;

- (RxObservable *)deleteByKeyInTxWithNSObjectArray:(IOSObjectArray *)keys;

- (RxObservable *)deleteInTxWithJavaLangIterable:(id<JavaLangIterable>)entities;

- (RxObservable *)deleteInTxWithNSObjectArray:(IOSObjectArray *)entities;

- (OrgGreenrobotGreendaoAbstractDao *)getDao;

- (RxObservable *)insertWithId:(id)entity;

- (RxObservable *)insertInTxWithJavaLangIterable:(id<JavaLangIterable>)entities;

- (RxObservable *)insertInTxWithNSObjectArray:(IOSObjectArray *)entities;

- (RxObservable *)insertOrReplaceWithId:(id)entity;

- (RxObservable *)insertOrReplaceInTxWithJavaLangIterable:(id<JavaLangIterable>)entities;

- (RxObservable *)insertOrReplaceInTxWithNSObjectArray:(IOSObjectArray *)entities;

- (RxObservable *)load__WithId:(id)key;

- (RxObservable *)loadAll;

- (RxObservable *)refreshWithId:(id)entity;

- (RxObservable *)saveWithId:(id)entity;

- (RxObservable *)saveInTxWithJavaLangIterable:(id<JavaLangIterable>)entities;

- (RxObservable *)saveInTxWithNSObjectArray:(IOSObjectArray *)entities;

- (RxObservable *)updateWithId:(id)entity;

- (RxObservable *)updateInTxWithJavaLangIterable:(id<JavaLangIterable>)entities;

- (RxObservable *)updateInTxWithNSObjectArray:(IOSObjectArray *)entities;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoRxRxDao)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoRxRxDao_initWithOrgGreenrobotGreendaoAbstractDao_(OrgGreenrobotGreendaoRxRxDao *self, OrgGreenrobotGreendaoAbstractDao *dao);

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxDao *new_OrgGreenrobotGreendaoRxRxDao_initWithOrgGreenrobotGreendaoAbstractDao_(OrgGreenrobotGreendaoAbstractDao *dao) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxDao *create_OrgGreenrobotGreendaoRxRxDao_initWithOrgGreenrobotGreendaoAbstractDao_(OrgGreenrobotGreendaoAbstractDao *dao);

FOUNDATION_EXPORT void OrgGreenrobotGreendaoRxRxDao_initWithOrgGreenrobotGreendaoAbstractDao_withRxScheduler_(OrgGreenrobotGreendaoRxRxDao *self, OrgGreenrobotGreendaoAbstractDao *dao, RxScheduler *scheduler);

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxDao *new_OrgGreenrobotGreendaoRxRxDao_initWithOrgGreenrobotGreendaoAbstractDao_withRxScheduler_(OrgGreenrobotGreendaoAbstractDao *dao, RxScheduler *scheduler) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxDao *create_OrgGreenrobotGreendaoRxRxDao_initWithOrgGreenrobotGreendaoAbstractDao_withRxScheduler_(OrgGreenrobotGreendaoAbstractDao *dao, RxScheduler *scheduler);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoRxRxDao)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoRxRxDao")
