//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PDSqldelightOpenHelperTest_MembersInjector")
#ifdef RESTRICT_PDSqldelightOpenHelperTest_MembersInjector
#define INCLUDE_ALL_PDSqldelightOpenHelperTest_MembersInjector 0
#else
#define INCLUDE_ALL_PDSqldelightOpenHelperTest_MembersInjector 1
#endif
#undef RESTRICT_PDSqldelightOpenHelperTest_MembersInjector

#if !defined (PDSqldelightOpenHelperTest_MembersInjector_) && (INCLUDE_ALL_PDSqldelightOpenHelperTest_MembersInjector || defined(INCLUDE_PDSqldelightOpenHelperTest_MembersInjector))
#define PDSqldelightOpenHelperTest_MembersInjector_

#define RESTRICT_DaggerMembersInjector 1
#define INCLUDE_DaggerMembersInjector 1
#include "DaggerMembersInjector.h"

@class PDSqldelightOpenHelperTest;
@protocol JavaxInjectProvider;

@interface PDSqldelightOpenHelperTest_MembersInjector : NSObject < DaggerMembersInjector >

#pragma mark Public

- (instancetype)initWithJavaxInjectProvider:(id<JavaxInjectProvider>)applicationProvider;

+ (id<DaggerMembersInjector>)createWithJavaxInjectProvider:(id<JavaxInjectProvider>)applicationProvider;

+ (void)injectApplicationWithPDSqldelightOpenHelperTest:(PDSqldelightOpenHelperTest *)instance
                                withJavaxInjectProvider:(id<JavaxInjectProvider>)applicationProvider;

- (void)injectMembersWithId:(PDSqldelightOpenHelperTest *)instance;

@end

J2OBJC_EMPTY_STATIC_INIT(PDSqldelightOpenHelperTest_MembersInjector)

FOUNDATION_EXPORT void PDSqldelightOpenHelperTest_MembersInjector_initWithJavaxInjectProvider_(PDSqldelightOpenHelperTest_MembersInjector *self, id<JavaxInjectProvider> applicationProvider);

FOUNDATION_EXPORT PDSqldelightOpenHelperTest_MembersInjector *new_PDSqldelightOpenHelperTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> applicationProvider) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDSqldelightOpenHelperTest_MembersInjector *create_PDSqldelightOpenHelperTest_MembersInjector_initWithJavaxInjectProvider_(id<JavaxInjectProvider> applicationProvider);

FOUNDATION_EXPORT id<DaggerMembersInjector> PDSqldelightOpenHelperTest_MembersInjector_createWithJavaxInjectProvider_(id<JavaxInjectProvider> applicationProvider);

FOUNDATION_EXPORT void PDSqldelightOpenHelperTest_MembersInjector_injectApplicationWithPDSqldelightOpenHelperTest_withJavaxInjectProvider_(PDSqldelightOpenHelperTest *instance, id<JavaxInjectProvider> applicationProvider);

J2OBJC_TYPE_LITERAL_HEADER(PDSqldelightOpenHelperTest_MembersInjector)

@compatibility_alias ComKgalliganPartyclickerDataSqldelightOpenHelperTest_MembersInjector PDSqldelightOpenHelperTest_MembersInjector;

#endif

#pragma pop_macro("INCLUDE_ALL_PDSqldelightOpenHelperTest_MembersInjector")
