//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryLazyList")
#ifdef RESTRICT_OrgGreenrobotGreendaoQueryLazyList
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryLazyList 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryLazyList 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoQueryLazyList

#if !defined (OrgGreenrobotGreendaoQueryLazyList_) && (INCLUDE_ALL_OrgGreenrobotGreendaoQueryLazyList || defined(INCLUDE_OrgGreenrobotGreendaoQueryLazyList))
#define OrgGreenrobotGreendaoQueryLazyList_

#define RESTRICT_JavaUtilList 1
#define INCLUDE_JavaUtilList 1
#include "java/util/List.h"

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

@class IOSObjectArray;
@class OrgGreenrobotGreendaoInternalQueryDaoAccess;
@protocol AndroidDatabaseCursor;
@protocol JavaUtilCollection;
@protocol JavaUtilComparator;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilFunctionPredicate;
@protocol JavaUtilFunctionUnaryOperator;
@protocol JavaUtilIterator;
@protocol JavaUtilListIterator;
@protocol JavaUtilSpliterator;
@protocol JavaUtilStreamStream;
@protocol OrgGreenrobotGreendaoQueryCloseableListIterator;

@interface OrgGreenrobotGreendaoQueryLazyList : NSObject < JavaUtilList, JavaIoCloseable >

#pragma mark Public

- (jboolean)addWithId:(id)object;

- (void)addWithInt:(jint)location
            withId:(id)object;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)arg0;

- (jboolean)addAllWithInt:(jint)arg0
   withJavaUtilCollection:(id<JavaUtilCollection>)arg1;

- (void)clear;

- (void)close;

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (id)getWithInt:(jint)location;

- (jint)getLoadedCount;

- (jint)indexOfWithId:(id)object;

- (jboolean)isClosed;

- (jboolean)isEmpty;

- (jboolean)isLoadedCompletely;

- (id<JavaUtilIterator>)iterator;

- (jint)lastIndexOfWithId:(id)object;

- (id<OrgGreenrobotGreendaoQueryCloseableListIterator>)listIterator;

- (id<JavaUtilListIterator>)listIteratorWithInt:(jint)location;

- (id<OrgGreenrobotGreendaoQueryCloseableListIterator>)listIteratorAutoClose;

- (void)loadRemaining;

- (id)peekWithInt:(jint)location;

- (id)removeWithInt:(jint)location;

- (jboolean)removeWithId:(id)object;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)arg0;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)arg0;

- (id)setWithInt:(jint)location
          withId:(id)object;

- (jint)size;

- (id<JavaUtilList>)subListWithInt:(jint)start
                           withInt:(jint)end;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

#pragma mark Protected

- (void)checkCached;

- (id)loadEntityWithInt:(jint)location;

#pragma mark Package-Private

- (instancetype)initWithOrgGreenrobotGreendaoInternalQueryDaoAccess:(OrgGreenrobotGreendaoInternalQueryDaoAccess *)daoAccess
                                          withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)cursor
                                                        withBoolean:(jboolean)cacheEntities;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoQueryLazyList)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoQueryLazyList_initWithOrgGreenrobotGreendaoInternalQueryDaoAccess_withAndroidDatabaseCursor_withBoolean_(OrgGreenrobotGreendaoQueryLazyList *self, OrgGreenrobotGreendaoInternalQueryDaoAccess *daoAccess, id<AndroidDatabaseCursor> cursor, jboolean cacheEntities);

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryLazyList *new_OrgGreenrobotGreendaoQueryLazyList_initWithOrgGreenrobotGreendaoInternalQueryDaoAccess_withAndroidDatabaseCursor_withBoolean_(OrgGreenrobotGreendaoInternalQueryDaoAccess *daoAccess, id<AndroidDatabaseCursor> cursor, jboolean cacheEntities) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryLazyList *create_OrgGreenrobotGreendaoQueryLazyList_initWithOrgGreenrobotGreendaoInternalQueryDaoAccess_withAndroidDatabaseCursor_withBoolean_(OrgGreenrobotGreendaoInternalQueryDaoAccess *daoAccess, id<AndroidDatabaseCursor> cursor, jboolean cacheEntities);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoQueryLazyList)

#endif

#if !defined (OrgGreenrobotGreendaoQueryLazyList_LazyIterator_) && (INCLUDE_ALL_OrgGreenrobotGreendaoQueryLazyList || defined(INCLUDE_OrgGreenrobotGreendaoQueryLazyList_LazyIterator))
#define OrgGreenrobotGreendaoQueryLazyList_LazyIterator_

#define RESTRICT_OrgGreenrobotGreendaoQueryCloseableListIterator 1
#define INCLUDE_OrgGreenrobotGreendaoQueryCloseableListIterator 1
#include "OrgGreenrobotGreendaoQueryCloseableListIterator.h"

@class OrgGreenrobotGreendaoQueryLazyList;
@protocol JavaUtilFunctionConsumer;

@interface OrgGreenrobotGreendaoQueryLazyList_LazyIterator : NSObject < OrgGreenrobotGreendaoQueryCloseableListIterator >

#pragma mark Public

- (instancetype)initWithOrgGreenrobotGreendaoQueryLazyList:(OrgGreenrobotGreendaoQueryLazyList *)outer$
                                                   withInt:(jint)startLocation
                                               withBoolean:(jboolean)closeWhenDone;

- (void)addWithId:(id)object;

- (void)close;

- (jboolean)hasNext;

- (jboolean)hasPrevious;

- (id)next;

- (jint)nextIndex;

- (id)previous;

- (jint)previousIndex;

- (void)remove;

- (void)setWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoQueryLazyList_LazyIterator)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoQueryLazyList_LazyIterator_initWithOrgGreenrobotGreendaoQueryLazyList_withInt_withBoolean_(OrgGreenrobotGreendaoQueryLazyList_LazyIterator *self, OrgGreenrobotGreendaoQueryLazyList *outer$, jint startLocation, jboolean closeWhenDone);

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryLazyList_LazyIterator *new_OrgGreenrobotGreendaoQueryLazyList_LazyIterator_initWithOrgGreenrobotGreendaoQueryLazyList_withInt_withBoolean_(OrgGreenrobotGreendaoQueryLazyList *outer$, jint startLocation, jboolean closeWhenDone) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryLazyList_LazyIterator *create_OrgGreenrobotGreendaoQueryLazyList_LazyIterator_initWithOrgGreenrobotGreendaoQueryLazyList_withInt_withBoolean_(OrgGreenrobotGreendaoQueryLazyList *outer$, jint startLocation, jboolean closeWhenDone);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoQueryLazyList_LazyIterator)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryLazyList")
