//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryWhereCollector")
#ifdef RESTRICT_OrgGreenrobotGreendaoQueryWhereCollector
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryWhereCollector 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryWhereCollector 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoQueryWhereCollector

#if !defined (OrgGreenrobotGreendaoQueryWhereCollector_) && (INCLUDE_ALL_OrgGreenrobotGreendaoQueryWhereCollector || defined(INCLUDE_OrgGreenrobotGreendaoQueryWhereCollector))
#define OrgGreenrobotGreendaoQueryWhereCollector_

@class IOSObjectArray;
@class JavaLangStringBuilder;
@class OrgGreenrobotGreendaoAbstractDao;
@class OrgGreenrobotGreendaoProperty;
@protocol JavaUtilList;
@protocol OrgGreenrobotGreendaoQueryWhereCondition;

@interface OrgGreenrobotGreendaoQueryWhereCollector : NSObject

#pragma mark Package-Private

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                            withNSString:(NSString *)tablePrefix;

- (void)addWithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond
      withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore;

- (void)addConditionWithJavaLangStringBuilder:(JavaLangStringBuilder *)builder
                             withJavaUtilList:(id<JavaUtilList>)values
 withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)condition;

- (void)appendWhereClauseWithJavaLangStringBuilder:(JavaLangStringBuilder *)builder
                                      withNSString:(NSString *)tablePrefixOrNull
                                  withJavaUtilList:(id<JavaUtilList>)values;

- (void)checkConditionWithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)whereCondition;

- (void)checkPropertyWithOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)property;

- (id<OrgGreenrobotGreendaoQueryWhereCondition>)combineWhereConditionsWithNSString:(NSString *)combineOp
                                      withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond1
                                      withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond2
                                 withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore;

- (jboolean)isEmpty;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoQueryWhereCollector)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoQueryWhereCollector_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_(OrgGreenrobotGreendaoQueryWhereCollector *self, OrgGreenrobotGreendaoAbstractDao *dao, NSString *tablePrefix);

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryWhereCollector *new_OrgGreenrobotGreendaoQueryWhereCollector_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *tablePrefix) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryWhereCollector *create_OrgGreenrobotGreendaoQueryWhereCollector_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *tablePrefix);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoQueryWhereCollector)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryWhereCollector")
