//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PDPersonModel")
#ifdef RESTRICT_PDPersonModel
#define INCLUDE_ALL_PDPersonModel 0
#else
#define INCLUDE_ALL_PDPersonModel 1
#endif
#undef RESTRICT_PDPersonModel

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PDPersonModel_) && (INCLUDE_ALL_PDPersonModel || defined(INCLUDE_PDPersonModel))
#define PDPersonModel_

@protocol PDPersonModel < JavaObject >

- (jlong)id__;

- (jlong)recorded;

- (jlong)val;

- (jlong)party;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPersonModel)

inline NSString *PDPersonModel_get_TABLE_NAME();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PDPersonModel_TABLE_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PDPersonModel, TABLE_NAME, NSString *)

inline NSString *PDPersonModel_get_ID();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PDPersonModel_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PDPersonModel, ID, NSString *)

inline NSString *PDPersonModel_get_RECORDED();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PDPersonModel_RECORDED;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PDPersonModel, RECORDED, NSString *)

inline NSString *PDPersonModel_get_VAL();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PDPersonModel_VAL;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PDPersonModel, VAL, NSString *)

inline NSString *PDPersonModel_get_PARTY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PDPersonModel_PARTY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PDPersonModel, PARTY, NSString *)

inline NSString *PDPersonModel_get_CREATE_TABLE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PDPersonModel_CREATE_TABLE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PDPersonModel, CREATE_TABLE, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(PDPersonModel)

#define ComKgalliganPartyclickerDataPersonModel PDPersonModel

#endif

#if !defined (PDPersonModel_Creator_) && (INCLUDE_ALL_PDPersonModel || defined(INCLUDE_PDPersonModel_Creator))
#define PDPersonModel_Creator_

@protocol PDPersonModel;

@protocol PDPersonModel_Creator < JavaObject >

- (id<PDPersonModel>)createWithLong:(jlong)id_
                           withLong:(jlong)recorded
                           withLong:(jlong)val
                           withLong:(jlong)party;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPersonModel_Creator)

J2OBJC_TYPE_LITERAL_HEADER(PDPersonModel_Creator)

#endif

#if !defined (PDPersonModel_Mapper_) && (INCLUDE_ALL_PDPersonModel || defined(INCLUDE_PDPersonModel_Mapper))
#define PDPersonModel_Mapper_

#define RESTRICT_ComSquareupSqldelightRowMapper 1
#define INCLUDE_ComSquareupSqldelightRowMapper 1
#include "ComSquareupSqldelightRowMapper.h"

@class PDPersonModel_Factory;
@protocol AndroidDatabaseCursor;
@protocol PDPersonModel;

@interface PDPersonModel_Mapper : NSObject < ComSquareupSqldelightRowMapper >

#pragma mark Public

- (instancetype)initWithPDPersonModel_Factory:(PDPersonModel_Factory *)personModelFactory;

- (id<PDPersonModel>)mapWithAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)cursor;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPersonModel_Mapper)

FOUNDATION_EXPORT void PDPersonModel_Mapper_initWithPDPersonModel_Factory_(PDPersonModel_Mapper *self, PDPersonModel_Factory *personModelFactory);

FOUNDATION_EXPORT PDPersonModel_Mapper *new_PDPersonModel_Mapper_initWithPDPersonModel_Factory_(PDPersonModel_Factory *personModelFactory) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDPersonModel_Mapper *create_PDPersonModel_Mapper_initWithPDPersonModel_Factory_(PDPersonModel_Factory *personModelFactory);

J2OBJC_TYPE_LITERAL_HEADER(PDPersonModel_Mapper)

#endif

#if !defined (PDPersonModel_Marshal_) && (INCLUDE_ALL_PDPersonModel || defined(INCLUDE_PDPersonModel_Marshal))
#define PDPersonModel_Marshal_

@class AndroidContentContentValues;
@protocol PDPersonModel;

@interface PDPersonModel_Marshal : NSObject {
 @public
  AndroidContentContentValues *contentValues_;
}

#pragma mark Public

- (AndroidContentContentValues *)asContentValues;

- (PDPersonModel_Marshal *)id__WithLong:(jlong)id_;

- (PDPersonModel_Marshal *)partyWithLong:(jlong)party;

- (PDPersonModel_Marshal *)recordedWithLong:(jlong)recorded;

- (PDPersonModel_Marshal *)valWithLong:(jlong)val;

#pragma mark Package-Private

- (instancetype)initWithPDPersonModel:(id<PDPersonModel>)copy_;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPersonModel_Marshal)

J2OBJC_FIELD_SETTER(PDPersonModel_Marshal, contentValues_, AndroidContentContentValues *)

FOUNDATION_EXPORT void PDPersonModel_Marshal_initWithPDPersonModel_(PDPersonModel_Marshal *self, id<PDPersonModel> copy_);

FOUNDATION_EXPORT PDPersonModel_Marshal *new_PDPersonModel_Marshal_initWithPDPersonModel_(id<PDPersonModel> copy_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDPersonModel_Marshal *create_PDPersonModel_Marshal_initWithPDPersonModel_(id<PDPersonModel> copy_);

J2OBJC_TYPE_LITERAL_HEADER(PDPersonModel_Marshal)

#endif

#if !defined (PDPersonModel_Factory_) && (INCLUDE_ALL_PDPersonModel || defined(INCLUDE_PDPersonModel_Factory))
#define PDPersonModel_Factory_

@class ComSquareupSqldelightSqlDelightStatement;
@class PDPersonModel_Mapper;
@class PDPersonModel_Marshal;
@protocol ComSquareupSqldelightRowMapper;
@protocol PDPersonModel;
@protocol PDPersonModel_Creator;

@interface PDPersonModel_Factory : NSObject {
 @public
  id<PDPersonModel_Creator> creator_;
}

#pragma mark Public

- (instancetype)initWithPDPersonModel_Creator:(id<PDPersonModel_Creator>)creator;

- (ComSquareupSqldelightSqlDelightStatement *)countPartyWithLong:(jlong)party;

- (id<ComSquareupSqldelightRowMapper>)countPartyMapper;

- (ComSquareupSqldelightSqlDelightStatement *)createPersonWithLong:(jlong)recorded
                                                          withLong:(jlong)val
                                                          withLong:(jlong)party;

- (PDPersonModel_Marshal *)marshal;

- (PDPersonModel_Marshal *)marshalWithPDPersonModel:(id<PDPersonModel>)copy_;

- (ComSquareupSqldelightSqlDelightStatement *)selectAll;

- (ComSquareupSqldelightSqlDelightStatement *)selectAllForPartyWithLong:(jlong)party;

- (PDPersonModel_Mapper *)selectAllForPartyMapper;

- (PDPersonModel_Mapper *)selectAllMapper;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPersonModel_Factory)

J2OBJC_FIELD_SETTER(PDPersonModel_Factory, creator_, id<PDPersonModel_Creator>)

FOUNDATION_EXPORT void PDPersonModel_Factory_initWithPDPersonModel_Creator_(PDPersonModel_Factory *self, id<PDPersonModel_Creator> creator);

FOUNDATION_EXPORT PDPersonModel_Factory *new_PDPersonModel_Factory_initWithPDPersonModel_Creator_(id<PDPersonModel_Creator> creator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDPersonModel_Factory *create_PDPersonModel_Factory_initWithPDPersonModel_Creator_(id<PDPersonModel_Creator> creator);

J2OBJC_TYPE_LITERAL_HEADER(PDPersonModel_Factory)

#endif

#if !defined (PDPersonModel_CreatePerson_) && (INCLUDE_ALL_PDPersonModel || defined(INCLUDE_PDPersonModel_CreatePerson))
#define PDPersonModel_CreatePerson_

#define RESTRICT_ComSquareupSqldelightSqlDelightCompiledStatement 1
#define INCLUDE_ComSquareupSqldelightSqlDelightCompiledStatement_Insert 1
#include "ComSquareupSqldelightSqlDelightCompiledStatement.h"

@class AndroidDatabaseSqliteSQLiteDatabase;

@interface PDPersonModel_CreatePerson : ComSquareupSqldelightSqlDelightCompiledStatement_Insert

#pragma mark Public

- (instancetype)initWithAndroidDatabaseSqliteSQLiteDatabase:(AndroidDatabaseSqliteSQLiteDatabase *)database;

- (void)bindWithLong:(jlong)recorded
            withLong:(jlong)val
            withLong:(jlong)party;

@end

J2OBJC_EMPTY_STATIC_INIT(PDPersonModel_CreatePerson)

FOUNDATION_EXPORT void PDPersonModel_CreatePerson_initWithAndroidDatabaseSqliteSQLiteDatabase_(PDPersonModel_CreatePerson *self, AndroidDatabaseSqliteSQLiteDatabase *database);

FOUNDATION_EXPORT PDPersonModel_CreatePerson *new_PDPersonModel_CreatePerson_initWithAndroidDatabaseSqliteSQLiteDatabase_(AndroidDatabaseSqliteSQLiteDatabase *database) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDPersonModel_CreatePerson *create_PDPersonModel_CreatePerson_initWithAndroidDatabaseSqliteSQLiteDatabase_(AndroidDatabaseSqliteSQLiteDatabase *database);

J2OBJC_TYPE_LITERAL_HEADER(PDPersonModel_CreatePerson)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_PDPersonModel")
