//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_source.h"
#include "PDPartyIntf.h"

@interface PDPartyIntf : NSObject

@end

@implementation PDPartyIntf

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "J", 0x401, 0, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(id__);
  methods[1].selector = @selector(name);
  methods[2].selector = @selector(created);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "id" };
  static const J2ObjcClassInfo _PDPartyIntf = { "PartyIntf", "com.kgalligan.partyclicker.data", ptrTable, methods, NULL, 7, 0x609, 3, 0, -1, -1, -1, -1, -1 };
  return &_PDPartyIntf;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(PDPartyIntf)
