//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PDParty")
#ifdef RESTRICT_PDParty
#define INCLUDE_ALL_PDParty 0
#else
#define INCLUDE_ALL_PDParty 1
#endif
#undef RESTRICT_PDParty

#if !defined (PDParty_) && (INCLUDE_ALL_PDParty || defined(INCLUDE_PDParty))
#define PDParty_

@class JavaLangLong;
@class JavaUtilDate;

@interface PDParty : NSObject {
 @public
  JavaLangLong *id__;
  NSString *name_;
  JavaUtilDate *created_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaLangLong:(JavaLangLong *)id_
                        withNSString:(NSString *)name
                    withJavaUtilDate:(JavaUtilDate *)created;

- (NSString *)dateString;

- (JavaUtilDate *)getCreated;

- (JavaLangLong *)getId;

- (NSString *)getName;

- (void)setCreatedWithJavaUtilDate:(JavaUtilDate *)created;

- (void)setIdWithJavaLangLong:(JavaLangLong *)id_;

- (void)setNameWithNSString:(NSString *)name;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(PDParty)

J2OBJC_FIELD_SETTER(PDParty, id__, JavaLangLong *)
J2OBJC_FIELD_SETTER(PDParty, name_, NSString *)
J2OBJC_FIELD_SETTER(PDParty, created_, JavaUtilDate *)

FOUNDATION_EXPORT void PDParty_initWithJavaLangLong_withNSString_withJavaUtilDate_(PDParty *self, JavaLangLong *id_, NSString *name, JavaUtilDate *created);

FOUNDATION_EXPORT PDParty *new_PDParty_initWithJavaLangLong_withNSString_withJavaUtilDate_(JavaLangLong *id_, NSString *name, JavaUtilDate *created) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDParty *create_PDParty_initWithJavaLangLong_withNSString_withJavaUtilDate_(JavaLangLong *id_, NSString *name, JavaUtilDate *created);

FOUNDATION_EXPORT void PDParty_init(PDParty *self);

FOUNDATION_EXPORT PDParty *new_PDParty_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PDParty *create_PDParty_init();

J2OBJC_TYPE_LITERAL_HEADER(PDParty)

@compatibility_alias ComKgalliganPartyclickerDataParty PDParty;

#endif

#pragma pop_macro("INCLUDE_ALL_PDParty")
