//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryQueryBuilder")
#ifdef RESTRICT_OrgGreenrobotGreendaoQueryQueryBuilder
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryQueryBuilder 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryQueryBuilder 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoQueryQueryBuilder

#if !defined (OrgGreenrobotGreendaoQueryQueryBuilder_) && (INCLUDE_ALL_OrgGreenrobotGreendaoQueryQueryBuilder || defined(INCLUDE_OrgGreenrobotGreendaoQueryQueryBuilder))
#define OrgGreenrobotGreendaoQueryQueryBuilder_

@class IOSClass;
@class IOSObjectArray;
@class JavaLangStringBuilder;
@class OrgGreenrobotGreendaoAbstractDao;
@class OrgGreenrobotGreendaoProperty;
@class OrgGreenrobotGreendaoQueryCountQuery;
@class OrgGreenrobotGreendaoQueryCursorQuery;
@class OrgGreenrobotGreendaoQueryDeleteQuery;
@class OrgGreenrobotGreendaoQueryJoin;
@class OrgGreenrobotGreendaoQueryLazyList;
@class OrgGreenrobotGreendaoQueryQuery;
@class OrgGreenrobotGreendaoRxRxQuery;
@protocol JavaUtilList;
@protocol OrgGreenrobotGreendaoQueryCloseableListIterator;
@protocol OrgGreenrobotGreendaoQueryWhereCondition;

@interface OrgGreenrobotGreendaoQueryQueryBuilder : NSObject

#pragma mark Public

- (id<OrgGreenrobotGreendaoQueryWhereCondition>)and__WithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond1
                                                     withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond2
                                                withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore;

- (OrgGreenrobotGreendaoQueryQuery *)build;

- (OrgGreenrobotGreendaoQueryCountQuery *)buildCount;

- (OrgGreenrobotGreendaoQueryCursorQuery *)buildCursor;

- (OrgGreenrobotGreendaoQueryDeleteQuery *)buildDelete;

- (jlong)count;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)distinct;

+ (OrgGreenrobotGreendaoQueryQueryBuilder *)internalCreateWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao;

- (OrgGreenrobotGreendaoQueryJoin *)joinWithIOSClass:(IOSClass *)destinationEntityClass
                   withOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)destinationProperty;

- (OrgGreenrobotGreendaoQueryJoin *)joinWithOrgGreenrobotGreendaoQueryJoin:(OrgGreenrobotGreendaoQueryJoin *)sourceJoin
                                         withOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)sourceProperty
                                                              withIOSClass:(IOSClass *)destinationEntityClass
                                         withOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)destinationProperty;

- (OrgGreenrobotGreendaoQueryJoin *)joinWithOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)sourceProperty
                                                             withIOSClass:(IOSClass *)destinationEntityClass;

- (OrgGreenrobotGreendaoQueryJoin *)joinWithOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)sourceProperty
                                                             withIOSClass:(IOSClass *)destinationEntityClass
                                        withOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)destinationProperty;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)limitWithInt:(jint)limit;

- (id<JavaUtilList>)list;

- (id<OrgGreenrobotGreendaoQueryCloseableListIterator>)listIterator;

- (OrgGreenrobotGreendaoQueryLazyList *)listLazy;

- (OrgGreenrobotGreendaoQueryLazyList *)listLazyUncached;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)offsetWithInt:(jint)offset;

- (id<OrgGreenrobotGreendaoQueryWhereCondition>)or__WithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond1
                                                    withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond2
                                               withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)orderAscWithOrgGreenrobotGreendaoPropertyArray:(IOSObjectArray *)properties;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)orderCustomWithOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)property
                                                                            withNSString:(NSString *)customOrderForProperty;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)orderDescWithOrgGreenrobotGreendaoPropertyArray:(IOSObjectArray *)properties;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)orderRawWithNSString:(NSString *)rawOrder;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)preferLocalizedStringOrder;

- (OrgGreenrobotGreendaoRxRxQuery *)rx;

- (OrgGreenrobotGreendaoRxRxQuery *)rxPlain;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)stringOrderCollationWithNSString:(NSString *)stringOrderCollation;

- (id)unique;

- (id)uniqueOrThrow;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)whereWithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond
                                            withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore;

- (OrgGreenrobotGreendaoQueryQueryBuilder *)whereOrWithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond1
                                                   withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond2
                                              withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore;

#pragma mark Protected

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao;

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                            withNSString:(NSString *)tablePrefix;

- (JavaLangStringBuilder *)appendWithJavaLangStringBuilder:(JavaLangStringBuilder *)builder
                         withOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)property;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoQueryQueryBuilder)

inline jboolean OrgGreenrobotGreendaoQueryQueryBuilder_get_LOG_SQL();
inline jboolean OrgGreenrobotGreendaoQueryQueryBuilder_set_LOG_SQL(jboolean value);
inline jboolean *OrgGreenrobotGreendaoQueryQueryBuilder_getRef_LOG_SQL();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jboolean OrgGreenrobotGreendaoQueryQueryBuilder_LOG_SQL;
J2OBJC_STATIC_FIELD_PRIMITIVE(OrgGreenrobotGreendaoQueryQueryBuilder, LOG_SQL, jboolean)

inline jboolean OrgGreenrobotGreendaoQueryQueryBuilder_get_LOG_VALUES();
inline jboolean OrgGreenrobotGreendaoQueryQueryBuilder_set_LOG_VALUES(jboolean value);
inline jboolean *OrgGreenrobotGreendaoQueryQueryBuilder_getRef_LOG_VALUES();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jboolean OrgGreenrobotGreendaoQueryQueryBuilder_LOG_VALUES;
J2OBJC_STATIC_FIELD_PRIMITIVE(OrgGreenrobotGreendaoQueryQueryBuilder, LOG_VALUES, jboolean)

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryQueryBuilder *OrgGreenrobotGreendaoQueryQueryBuilder_internalCreateWithOrgGreenrobotGreendaoAbstractDao_(OrgGreenrobotGreendaoAbstractDao *dao);

FOUNDATION_EXPORT void OrgGreenrobotGreendaoQueryQueryBuilder_initWithOrgGreenrobotGreendaoAbstractDao_(OrgGreenrobotGreendaoQueryQueryBuilder *self, OrgGreenrobotGreendaoAbstractDao *dao);

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryQueryBuilder *new_OrgGreenrobotGreendaoQueryQueryBuilder_initWithOrgGreenrobotGreendaoAbstractDao_(OrgGreenrobotGreendaoAbstractDao *dao) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryQueryBuilder *create_OrgGreenrobotGreendaoQueryQueryBuilder_initWithOrgGreenrobotGreendaoAbstractDao_(OrgGreenrobotGreendaoAbstractDao *dao);

FOUNDATION_EXPORT void OrgGreenrobotGreendaoQueryQueryBuilder_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_(OrgGreenrobotGreendaoQueryQueryBuilder *self, OrgGreenrobotGreendaoAbstractDao *dao, NSString *tablePrefix);

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryQueryBuilder *new_OrgGreenrobotGreendaoQueryQueryBuilder_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *tablePrefix) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryQueryBuilder *create_OrgGreenrobotGreendaoQueryQueryBuilder_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *tablePrefix);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoQueryQueryBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryQueryBuilder")
