//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement")
#ifdef RESTRICT_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement
#define INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement

#if !defined (OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement_) && (INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement || defined(INCLUDE_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement))
#define OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement_

#define RESTRICT_OrgGreenrobotGreendaoDatabaseDatabaseStatement 1
#define INCLUDE_OrgGreenrobotGreendaoDatabaseDatabaseStatement 1
#include "OrgGreenrobotGreendaoDatabaseDatabaseStatement.h"

@class IOSByteArray;
@class NetSqlcipherDatabaseSQLiteStatement;

@interface OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement : NSObject < OrgGreenrobotGreendaoDatabaseDatabaseStatement >

#pragma mark Public

- (instancetype)initWithNetSqlcipherDatabaseSQLiteStatement:(NetSqlcipherDatabaseSQLiteStatement *)delegate;

- (void)bindBlobWithInt:(jint)index
          withByteArray:(IOSByteArray *)value;

- (void)bindDoubleWithInt:(jint)index
               withDouble:(jdouble)value;

- (void)bindLongWithInt:(jint)index
               withLong:(jlong)value;

- (void)bindNullWithInt:(jint)index;

- (void)bindStringWithInt:(jint)index
             withNSString:(NSString *)value;

- (void)clearBindings;

- (void)close;

- (void)execute;

- (jlong)executeInsert;

- (id)getRawStatement;

- (jlong)simpleQueryForLong;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement_initWithNetSqlcipherDatabaseSQLiteStatement_(OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement *self, NetSqlcipherDatabaseSQLiteStatement *delegate);

FOUNDATION_EXPORT OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement *new_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement_initWithNetSqlcipherDatabaseSQLiteStatement_(NetSqlcipherDatabaseSQLiteStatement *delegate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement *create_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement_initWithNetSqlcipherDatabaseSQLiteStatement_(NetSqlcipherDatabaseSQLiteStatement *delegate);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseEncryptedDatabaseStatement")
