//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoRxRxQuery")
#ifdef RESTRICT_OrgGreenrobotGreendaoRxRxQuery
#define INCLUDE_ALL_OrgGreenrobotGreendaoRxRxQuery 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoRxRxQuery 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoRxRxQuery

#if !defined (OrgGreenrobotGreendaoRxRxQuery_) && (INCLUDE_ALL_OrgGreenrobotGreendaoRxRxQuery || defined(INCLUDE_OrgGreenrobotGreendaoRxRxQuery))
#define OrgGreenrobotGreendaoRxRxQuery_

#define RESTRICT_OrgGreenrobotGreendaoRxRxBase 1
#define INCLUDE_OrgGreenrobotGreendaoRxRxBase 1
#include "OrgGreenrobotGreendaoRxRxBase.h"

@class OrgGreenrobotGreendaoQueryQuery;
@class RxObservable;
@class RxScheduler;

@interface OrgGreenrobotGreendaoRxRxQuery : OrgGreenrobotGreendaoRxRxBase

#pragma mark Public

- (instancetype)initWithOrgGreenrobotGreendaoQueryQuery:(OrgGreenrobotGreendaoQueryQuery *)query;

- (instancetype)initWithOrgGreenrobotGreendaoQueryQuery:(OrgGreenrobotGreendaoQueryQuery *)query
                                        withRxScheduler:(RxScheduler *)scheduler;

- (RxObservable *)list;

- (RxObservable *)oneByOne;

- (RxObservable *)unique;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoRxRxQuery)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoRxRxQuery_initWithOrgGreenrobotGreendaoQueryQuery_(OrgGreenrobotGreendaoRxRxQuery *self, OrgGreenrobotGreendaoQueryQuery *query);

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxQuery *new_OrgGreenrobotGreendaoRxRxQuery_initWithOrgGreenrobotGreendaoQueryQuery_(OrgGreenrobotGreendaoQueryQuery *query) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxQuery *create_OrgGreenrobotGreendaoRxRxQuery_initWithOrgGreenrobotGreendaoQueryQuery_(OrgGreenrobotGreendaoQueryQuery *query);

FOUNDATION_EXPORT void OrgGreenrobotGreendaoRxRxQuery_initWithOrgGreenrobotGreendaoQueryQuery_withRxScheduler_(OrgGreenrobotGreendaoRxRxQuery *self, OrgGreenrobotGreendaoQueryQuery *query, RxScheduler *scheduler);

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxQuery *new_OrgGreenrobotGreendaoRxRxQuery_initWithOrgGreenrobotGreendaoQueryQuery_withRxScheduler_(OrgGreenrobotGreendaoQueryQuery *query, RxScheduler *scheduler) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoRxRxQuery *create_OrgGreenrobotGreendaoRxRxQuery_initWithOrgGreenrobotGreendaoQueryQuery_withRxScheduler_(OrgGreenrobotGreendaoQueryQuery *query, RxScheduler *scheduler);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoRxRxQuery)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoRxRxQuery")
