//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryAbstractQueryData")
#ifdef RESTRICT_OrgGreenrobotGreendaoQueryAbstractQueryData
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryAbstractQueryData 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryAbstractQueryData 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoQueryAbstractQueryData

#if !defined (OrgGreenrobotGreendaoQueryAbstractQueryData_) && (INCLUDE_ALL_OrgGreenrobotGreendaoQueryAbstractQueryData || defined(INCLUDE_OrgGreenrobotGreendaoQueryAbstractQueryData))
#define OrgGreenrobotGreendaoQueryAbstractQueryData_

@class IOSObjectArray;
@class OrgGreenrobotGreendaoAbstractDao;
@class OrgGreenrobotGreendaoQueryAbstractQuery;
@protocol JavaUtilMap;

@interface OrgGreenrobotGreendaoQueryAbstractQueryData : NSObject {
 @public
  NSString *sql_;
  OrgGreenrobotGreendaoAbstractDao *dao_;
  IOSObjectArray *initialValues_;
  id<JavaUtilMap> queriesForThreads_;
}

#pragma mark Protected

- (OrgGreenrobotGreendaoQueryAbstractQuery *)createQuery;

#pragma mark Package-Private

- (instancetype)initWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                            withNSString:(NSString *)sql
                                       withNSStringArray:(IOSObjectArray *)initialValues;

- (OrgGreenrobotGreendaoQueryAbstractQuery *)forCurrentThread;

- (OrgGreenrobotGreendaoQueryAbstractQuery *)forCurrentThreadWithOrgGreenrobotGreendaoQueryAbstractQuery:(OrgGreenrobotGreendaoQueryAbstractQuery *)query;

- (void)gc;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoQueryAbstractQueryData)

J2OBJC_FIELD_SETTER(OrgGreenrobotGreendaoQueryAbstractQueryData, sql_, NSString *)
J2OBJC_FIELD_SETTER(OrgGreenrobotGreendaoQueryAbstractQueryData, dao_, OrgGreenrobotGreendaoAbstractDao *)
J2OBJC_FIELD_SETTER(OrgGreenrobotGreendaoQueryAbstractQueryData, initialValues_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgGreenrobotGreendaoQueryAbstractQueryData, queriesForThreads_, id<JavaUtilMap>)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoQueryAbstractQueryData_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSStringArray_(OrgGreenrobotGreendaoQueryAbstractQueryData *self, OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoQueryAbstractQueryData)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryAbstractQueryData")
