//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_source.h"
#include "OrgGreenrobotGreendaoDatabaseDatabase.h"

@interface OrgGreenrobotGreendaoDatabaseDatabase : NSObject

@end

@implementation OrgGreenrobotGreendaoDatabaseDatabase

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LAndroidDatabaseCursor;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, 4, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 5, 4, -1, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoDatabaseDatabaseStatement;", 0x401, 6, 3, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(rawQueryWithNSString:withNSStringArray:);
  methods[1].selector = @selector(execSQLWithNSString:);
  methods[2].selector = @selector(beginTransaction);
  methods[3].selector = @selector(endTransaction);
  methods[4].selector = @selector(inTransaction);
  methods[5].selector = @selector(setTransactionSuccessful);
  methods[6].selector = @selector(execSQLWithNSString:withNSObjectArray:);
  methods[7].selector = @selector(compileStatementWithNSString:);
  methods[8].selector = @selector(isDbLockedByCurrentThread);
  methods[9].selector = @selector(close);
  methods[10].selector = @selector(getRawDatabase);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "rawQuery", "LNSString;[LNSString;", "execSQL", "LNSString;", "LAndroidDatabaseSQLException;", "LNSString;[LNSObject;", "compileStatement" };
  static const J2ObjcClassInfo _OrgGreenrobotGreendaoDatabaseDatabase = { "Database", "org.greenrobot.greendao.database", ptrTable, methods, NULL, 7, 0x609, 11, 0, -1, -1, -1, -1, -1 };
  return &_OrgGreenrobotGreendaoDatabaseDatabase;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgGreenrobotGreendaoDatabaseDatabase)
