//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryCursorQuery")
#ifdef RESTRICT_OrgGreenrobotGreendaoQueryCursorQuery
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryCursorQuery 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoQueryCursorQuery 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoQueryCursorQuery

#if !defined (OrgGreenrobotGreendaoQueryCursorQuery_) && (INCLUDE_ALL_OrgGreenrobotGreendaoQueryCursorQuery || defined(INCLUDE_OrgGreenrobotGreendaoQueryCursorQuery))
#define OrgGreenrobotGreendaoQueryCursorQuery_

#define RESTRICT_OrgGreenrobotGreendaoQueryAbstractQueryWithLimit 1
#define INCLUDE_OrgGreenrobotGreendaoQueryAbstractQueryWithLimit 1
#include "OrgGreenrobotGreendaoQueryAbstractQueryWithLimit.h"

@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaUtilDate;
@class OrgGreenrobotGreendaoAbstractDao;
@protocol AndroidDatabaseCursor;

@interface OrgGreenrobotGreendaoQueryCursorQuery : OrgGreenrobotGreendaoQueryAbstractQueryWithLimit

#pragma mark Public

- (OrgGreenrobotGreendaoQueryCursorQuery *)forCurrentThread;

+ (OrgGreenrobotGreendaoQueryCursorQuery *)internalCreateWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                                                                 withNSString:(NSString *)sql
                                                                            withNSObjectArray:(IOSObjectArray *)initialValues;

- (id<AndroidDatabaseCursor>)query;

- (OrgGreenrobotGreendaoQueryCursorQuery *)setParameterWithInt:(jint)index
                                           withJavaLangBoolean:(JavaLangBoolean *)parameter;

- (OrgGreenrobotGreendaoQueryCursorQuery *)setParameterWithInt:(jint)index
                                              withJavaUtilDate:(JavaUtilDate *)parameter;

- (OrgGreenrobotGreendaoQueryCursorQuery *)setParameterWithInt:(jint)index
                                                        withId:(id)parameter;

#pragma mark Package-Private

+ (OrgGreenrobotGreendaoQueryCursorQuery *)createWithOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)dao
                                                                         withNSString:(NSString *)sql
                                                                    withNSObjectArray:(IOSObjectArray *)initialValues
                                                                              withInt:(jint)limitPosition
                                                                              withInt:(jint)offsetPosition;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoQueryCursorQuery)

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryCursorQuery *OrgGreenrobotGreendaoQueryCursorQuery_internalCreateWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSObjectArray_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues);

FOUNDATION_EXPORT OrgGreenrobotGreendaoQueryCursorQuery *OrgGreenrobotGreendaoQueryCursorQuery_createWithOrgGreenrobotGreendaoAbstractDao_withNSString_withNSObjectArray_withInt_withInt_(OrgGreenrobotGreendaoAbstractDao *dao, NSString *sql, IOSObjectArray *initialValues, jint limitPosition, jint offsetPosition);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoQueryCursorQuery)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoQueryCursorQuery")
