//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "AndroidDatabaseSQLException.h"
#include "J2ObjC_source.h"
#include "OrgGreenrobotGreendaoDaoException.h"
#include "OrgGreenrobotGreendaoDaoLog.h"

inline jlong OrgGreenrobotGreendaoDaoException_get_serialVersionUID();
#define OrgGreenrobotGreendaoDaoException_serialVersionUID -5877937327907457779LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgGreenrobotGreendaoDaoException, serialVersionUID, jlong)

@implementation OrgGreenrobotGreendaoDaoException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgGreenrobotGreendaoDaoException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)error {
  OrgGreenrobotGreendaoDaoException_initWithNSString_(self, error);
  return self;
}

- (instancetype)initWithNSString:(NSString *)error
                 withNSException:(NSException *)cause {
  OrgGreenrobotGreendaoDaoException_initWithNSString_withNSException_(self, error, cause);
  return self;
}

- (instancetype)initWithNSException:(NSException *)th {
  OrgGreenrobotGreendaoDaoException_initWithNSException_(self, th);
  return self;
}

- (void)safeInitCauseWithNSException:(NSException *)cause {
  @try {
    [self initCauseWithNSException:cause];
  }
  @catch (NSException *e) {
    OrgGreenrobotGreendaoDaoLog_eWithNSString_withNSException_(@"Could not set initial cause", e);
    OrgGreenrobotGreendaoDaoLog_eWithNSString_withNSException_(@"Initial cause is:", cause);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 3, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(initWithNSString:withNSException:);
  methods[3].selector = @selector(initWithNSException:);
  methods[4].selector = @selector(safeInitCauseWithNSException:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = OrgGreenrobotGreendaoDaoException_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LNSString;LNSException;", "LNSException;", "safeInitCause" };
  static const J2ObjcClassInfo _OrgGreenrobotGreendaoDaoException = { "DaoException", "org.greenrobot.greendao", ptrTable, methods, fields, 7, 0x1, 5, 1, -1, -1, -1, -1, -1 };
  return &_OrgGreenrobotGreendaoDaoException;
}

@end

void OrgGreenrobotGreendaoDaoException_init(OrgGreenrobotGreendaoDaoException *self) {
  AndroidDatabaseSQLException_init(self);
}

OrgGreenrobotGreendaoDaoException *new_OrgGreenrobotGreendaoDaoException_init() {
  J2OBJC_NEW_IMPL(OrgGreenrobotGreendaoDaoException, init)
}

OrgGreenrobotGreendaoDaoException *create_OrgGreenrobotGreendaoDaoException_init() {
  J2OBJC_CREATE_IMPL(OrgGreenrobotGreendaoDaoException, init)
}

void OrgGreenrobotGreendaoDaoException_initWithNSString_(OrgGreenrobotGreendaoDaoException *self, NSString *error) {
  AndroidDatabaseSQLException_initWithNSString_(self, error);
}

OrgGreenrobotGreendaoDaoException *new_OrgGreenrobotGreendaoDaoException_initWithNSString_(NSString *error) {
  J2OBJC_NEW_IMPL(OrgGreenrobotGreendaoDaoException, initWithNSString_, error)
}

OrgGreenrobotGreendaoDaoException *create_OrgGreenrobotGreendaoDaoException_initWithNSString_(NSString *error) {
  J2OBJC_CREATE_IMPL(OrgGreenrobotGreendaoDaoException, initWithNSString_, error)
}

void OrgGreenrobotGreendaoDaoException_initWithNSString_withNSException_(OrgGreenrobotGreendaoDaoException *self, NSString *error, NSException *cause) {
  AndroidDatabaseSQLException_initWithNSString_(self, error);
  [self safeInitCauseWithNSException:cause];
}

OrgGreenrobotGreendaoDaoException *new_OrgGreenrobotGreendaoDaoException_initWithNSString_withNSException_(NSString *error, NSException *cause) {
  J2OBJC_NEW_IMPL(OrgGreenrobotGreendaoDaoException, initWithNSString_withNSException_, error, cause)
}

OrgGreenrobotGreendaoDaoException *create_OrgGreenrobotGreendaoDaoException_initWithNSString_withNSException_(NSString *error, NSException *cause) {
  J2OBJC_CREATE_IMPL(OrgGreenrobotGreendaoDaoException, initWithNSString_withNSException_, error, cause)
}

void OrgGreenrobotGreendaoDaoException_initWithNSException_(OrgGreenrobotGreendaoDaoException *self, NSException *th) {
  AndroidDatabaseSQLException_init(self);
  [self safeInitCauseWithNSException:th];
}

OrgGreenrobotGreendaoDaoException *new_OrgGreenrobotGreendaoDaoException_initWithNSException_(NSException *th) {
  J2OBJC_NEW_IMPL(OrgGreenrobotGreendaoDaoException, initWithNSException_, th)
}

OrgGreenrobotGreendaoDaoException *create_OrgGreenrobotGreendaoDaoException_initWithNSException_(NSException *th) {
  J2OBJC_CREATE_IMPL(OrgGreenrobotGreendaoDaoException, initWithNSException_, th)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGreenrobotGreendaoDaoException)
