//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OrgGreenrobotGreendaoAbstractDao.h"
#include "OrgGreenrobotGreendaoProperty.h"
#include "OrgGreenrobotGreendaoQueryJoin.h"
#include "OrgGreenrobotGreendaoQueryWhereCollector.h"
#include "OrgGreenrobotGreendaoQueryWhereCondition.h"

@implementation OrgGreenrobotGreendaoQueryJoin

- (instancetype)initWithNSString:(NSString *)sourceTablePrefix
withOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)sourceJoinProperty
withOrgGreenrobotGreendaoAbstractDao:(OrgGreenrobotGreendaoAbstractDao *)daoDestination
withOrgGreenrobotGreendaoProperty:(OrgGreenrobotGreendaoProperty *)destinationJoinProperty
                    withNSString:(NSString *)joinTablePrefix {
  OrgGreenrobotGreendaoQueryJoin_initWithNSString_withOrgGreenrobotGreendaoProperty_withOrgGreenrobotGreendaoAbstractDao_withOrgGreenrobotGreendaoProperty_withNSString_(self, sourceTablePrefix, sourceJoinProperty, daoDestination, destinationJoinProperty, joinTablePrefix);
  return self;
}

- (OrgGreenrobotGreendaoQueryJoin *)whereWithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond
                                    withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore {
  [((OrgGreenrobotGreendaoQueryWhereCollector *) nil_chk(whereCollector_)) addWithOrgGreenrobotGreendaoQueryWhereCondition:cond withOrgGreenrobotGreendaoQueryWhereConditionArray:condMore];
  return self;
}

- (OrgGreenrobotGreendaoQueryJoin *)whereOrWithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond1
                                           withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond2
                                      withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore {
  [((OrgGreenrobotGreendaoQueryWhereCollector *) nil_chk(whereCollector_)) addWithOrgGreenrobotGreendaoQueryWhereCondition:[self or__WithOrgGreenrobotGreendaoQueryWhereCondition:cond1 withOrgGreenrobotGreendaoQueryWhereCondition:cond2 withOrgGreenrobotGreendaoQueryWhereConditionArray:condMore] withOrgGreenrobotGreendaoQueryWhereConditionArray:[IOSObjectArray arrayWithLength:0 type:OrgGreenrobotGreendaoQueryWhereCondition_class_()]];
  return self;
}

- (id<OrgGreenrobotGreendaoQueryWhereCondition>)or__WithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond1
                                                    withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond2
                                               withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore {
  return [((OrgGreenrobotGreendaoQueryWhereCollector *) nil_chk(whereCollector_)) combineWhereConditionsWithNSString:@" OR " withOrgGreenrobotGreendaoQueryWhereCondition:cond1 withOrgGreenrobotGreendaoQueryWhereCondition:cond2 withOrgGreenrobotGreendaoQueryWhereConditionArray:condMore];
}

- (id<OrgGreenrobotGreendaoQueryWhereCondition>)and__WithOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond1
                                                     withOrgGreenrobotGreendaoQueryWhereCondition:(id<OrgGreenrobotGreendaoQueryWhereCondition>)cond2
                                                withOrgGreenrobotGreendaoQueryWhereConditionArray:(IOSObjectArray *)condMore {
  return [((OrgGreenrobotGreendaoQueryWhereCollector *) nil_chk(whereCollector_)) combineWhereConditionsWithNSString:@" AND " withOrgGreenrobotGreendaoQueryWhereCondition:cond1 withOrgGreenrobotGreendaoQueryWhereCondition:cond2 withOrgGreenrobotGreendaoQueryWhereConditionArray:condMore];
}

- (NSString *)getTablePrefix {
  return tablePrefix_;
}

- (void)dealloc {
  RELEASE_(sourceTablePrefix_);
  RELEASE_(daoDestination_);
  RELEASE_(joinPropertySource_);
  RELEASE_(joinPropertyDestination_);
  RELEASE_(tablePrefix_);
  RELEASE_(whereCollector_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryJoin;", 0x81, 2, 3, -1, 4, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryJoin;", 0x81, 5, 6, -1, 7, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryWhereCondition;", 0x81, 8, 6, -1, -1, -1, -1 },
    { NULL, "LOrgGreenrobotGreendaoQueryWhereCondition;", 0x81, 9, 6, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:withOrgGreenrobotGreendaoProperty:withOrgGreenrobotGreendaoAbstractDao:withOrgGreenrobotGreendaoProperty:withNSString:);
  methods[1].selector = @selector(whereWithOrgGreenrobotGreendaoQueryWhereCondition:withOrgGreenrobotGreendaoQueryWhereConditionArray:);
  methods[2].selector = @selector(whereOrWithOrgGreenrobotGreendaoQueryWhereCondition:withOrgGreenrobotGreendaoQueryWhereCondition:withOrgGreenrobotGreendaoQueryWhereConditionArray:);
  methods[3].selector = @selector(or__WithOrgGreenrobotGreendaoQueryWhereCondition:withOrgGreenrobotGreendaoQueryWhereCondition:withOrgGreenrobotGreendaoQueryWhereConditionArray:);
  methods[4].selector = @selector(and__WithOrgGreenrobotGreendaoQueryWhereCondition:withOrgGreenrobotGreendaoQueryWhereCondition:withOrgGreenrobotGreendaoQueryWhereConditionArray:);
  methods[5].selector = @selector(getTablePrefix);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "sourceTablePrefix_", "LNSString;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "daoDestination_", "LOrgGreenrobotGreendaoAbstractDao;", .constantValue.asLong = 0, 0x10, -1, -1, 10, -1 },
    { "joinPropertySource_", "LOrgGreenrobotGreendaoProperty;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "joinPropertyDestination_", "LOrgGreenrobotGreendaoProperty;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "tablePrefix_", "LNSString;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "whereCollector_", "LOrgGreenrobotGreendaoQueryWhereCollector;", .constantValue.asLong = 0, 0x10, -1, -1, 11, -1 },
  };
  static const void *ptrTable[] = { "LNSString;LOrgGreenrobotGreendaoProperty;LOrgGreenrobotGreendaoAbstractDao;LOrgGreenrobotGreendaoProperty;LNSString;", "(Ljava/lang/String;Lorg/greenrobot/greendao/Property;Lorg/greenrobot/greendao/AbstractDao<TDST;*>;Lorg/greenrobot/greendao/Property;Ljava/lang/String;)V", "where", "LOrgGreenrobotGreendaoQueryWhereCondition;[LOrgGreenrobotGreendaoQueryWhereCondition;", "(Lorg/greenrobot/greendao/query/WhereCondition;[Lorg/greenrobot/greendao/query/WhereCondition;)Lorg/greenrobot/greendao/query/Join<TSRC;TDST;>;", "whereOr", "LOrgGreenrobotGreendaoQueryWhereCondition;LOrgGreenrobotGreendaoQueryWhereCondition;[LOrgGreenrobotGreendaoQueryWhereCondition;", "(Lorg/greenrobot/greendao/query/WhereCondition;Lorg/greenrobot/greendao/query/WhereCondition;[Lorg/greenrobot/greendao/query/WhereCondition;)Lorg/greenrobot/greendao/query/Join<TSRC;TDST;>;", "or", "and", "Lorg/greenrobot/greendao/AbstractDao<TDST;*>;", "Lorg/greenrobot/greendao/query/WhereCollector<TDST;>;", "<SRC:Ljava/lang/Object;DST:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _OrgGreenrobotGreendaoQueryJoin = { "Join", "org.greenrobot.greendao.query", ptrTable, methods, fields, 7, 0x1, 6, 6, -1, -1, -1, 12, -1 };
  return &_OrgGreenrobotGreendaoQueryJoin;
}

@end

void OrgGreenrobotGreendaoQueryJoin_initWithNSString_withOrgGreenrobotGreendaoProperty_withOrgGreenrobotGreendaoAbstractDao_withOrgGreenrobotGreendaoProperty_withNSString_(OrgGreenrobotGreendaoQueryJoin *self, NSString *sourceTablePrefix, OrgGreenrobotGreendaoProperty *sourceJoinProperty, OrgGreenrobotGreendaoAbstractDao *daoDestination, OrgGreenrobotGreendaoProperty *destinationJoinProperty, NSString *joinTablePrefix) {
  NSObject_init(self);
  JreStrongAssign(&self->sourceTablePrefix_, sourceTablePrefix);
  JreStrongAssign(&self->joinPropertySource_, sourceJoinProperty);
  JreStrongAssign(&self->daoDestination_, daoDestination);
  JreStrongAssign(&self->joinPropertyDestination_, destinationJoinProperty);
  JreStrongAssign(&self->tablePrefix_, joinTablePrefix);
  JreStrongAssignAndConsume(&self->whereCollector_, new_OrgGreenrobotGreendaoQueryWhereCollector_initWithOrgGreenrobotGreendaoAbstractDao_withNSString_(daoDestination, joinTablePrefix));
}

OrgGreenrobotGreendaoQueryJoin *new_OrgGreenrobotGreendaoQueryJoin_initWithNSString_withOrgGreenrobotGreendaoProperty_withOrgGreenrobotGreendaoAbstractDao_withOrgGreenrobotGreendaoProperty_withNSString_(NSString *sourceTablePrefix, OrgGreenrobotGreendaoProperty *sourceJoinProperty, OrgGreenrobotGreendaoAbstractDao *daoDestination, OrgGreenrobotGreendaoProperty *destinationJoinProperty, NSString *joinTablePrefix) {
  J2OBJC_NEW_IMPL(OrgGreenrobotGreendaoQueryJoin, initWithNSString_withOrgGreenrobotGreendaoProperty_withOrgGreenrobotGreendaoAbstractDao_withOrgGreenrobotGreendaoProperty_withNSString_, sourceTablePrefix, sourceJoinProperty, daoDestination, destinationJoinProperty, joinTablePrefix)
}

OrgGreenrobotGreendaoQueryJoin *create_OrgGreenrobotGreendaoQueryJoin_initWithNSString_withOrgGreenrobotGreendaoProperty_withOrgGreenrobotGreendaoAbstractDao_withOrgGreenrobotGreendaoProperty_withNSString_(NSString *sourceTablePrefix, OrgGreenrobotGreendaoProperty *sourceJoinProperty, OrgGreenrobotGreendaoAbstractDao *daoDestination, OrgGreenrobotGreendaoProperty *destinationJoinProperty, NSString *joinTablePrefix) {
  J2OBJC_CREATE_IMPL(OrgGreenrobotGreendaoQueryJoin, initWithNSString_withOrgGreenrobotGreendaoProperty_withOrgGreenrobotGreendaoAbstractDao_withOrgGreenrobotGreendaoProperty_withNSString_, sourceTablePrefix, sourceJoinProperty, daoDestination, destinationJoinProperty, joinTablePrefix)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGreenrobotGreendaoQueryJoin)
