//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement")
#ifdef RESTRICT_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement
#define INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement

#if !defined (OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement_) && (INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement || defined(INCLUDE_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement))
#define OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement_

#define RESTRICT_OrgGreenrobotGreendaoDatabaseDatabaseStatement 1
#define INCLUDE_OrgGreenrobotGreendaoDatabaseDatabaseStatement 1
#include "OrgGreenrobotGreendaoDatabaseDatabaseStatement.h"

@class AndroidDatabaseSqliteSQLiteStatement;
@class IOSByteArray;

@interface OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement : NSObject < OrgGreenrobotGreendaoDatabaseDatabaseStatement >

#pragma mark Public

- (instancetype)initWithAndroidDatabaseSqliteSQLiteStatement:(AndroidDatabaseSqliteSQLiteStatement *)delegate;

- (void)bindBlobWithInt:(jint)index
          withByteArray:(IOSByteArray *)value;

- (void)bindDoubleWithInt:(jint)index
               withDouble:(jdouble)value;

- (void)bindLongWithInt:(jint)index
               withLong:(jlong)value;

- (void)bindNullWithInt:(jint)index;

- (void)bindStringWithInt:(jint)index
             withNSString:(NSString *)value;

- (void)clearBindings;

- (void)close;

- (void)execute;

- (jlong)executeInsert;

- (id)getRawStatement;

- (jlong)simpleQueryForLong;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement)

FOUNDATION_EXPORT void OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement_initWithAndroidDatabaseSqliteSQLiteStatement_(OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement *self, AndroidDatabaseSqliteSQLiteStatement *delegate);

FOUNDATION_EXPORT OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement *new_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement_initWithAndroidDatabaseSqliteSQLiteStatement_(AndroidDatabaseSqliteSQLiteStatement *delegate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement *create_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement_initWithAndroidDatabaseSqliteSQLiteStatement_(AndroidDatabaseSqliteSQLiteStatement *delegate);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseStandardDatabaseStatement")
