//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType")
#ifdef RESTRICT_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType
#define INCLUDE_ALL_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_) && (INCLUDE_ALL_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType || defined(INCLUDE_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType))
#define OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_Enum) {
  OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_Enum_Session = 0,
  OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_Enum_None = 1,
};

@interface OrgGreenrobotGreendaoIdentityscopeIdentityScopeType : JavaLangEnum < NSCopying >

#pragma mark Public

+ (OrgGreenrobotGreendaoIdentityscopeIdentityScopeType *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(OrgGreenrobotGreendaoIdentityscopeIdentityScopeType)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgGreenrobotGreendaoIdentityscopeIdentityScopeType *OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_values_[];

inline OrgGreenrobotGreendaoIdentityscopeIdentityScopeType *OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_get_Session();
J2OBJC_ENUM_CONSTANT(OrgGreenrobotGreendaoIdentityscopeIdentityScopeType, Session)

inline OrgGreenrobotGreendaoIdentityscopeIdentityScopeType *OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_get_None();
J2OBJC_ENUM_CONSTANT(OrgGreenrobotGreendaoIdentityscopeIdentityScopeType, None)

FOUNDATION_EXPORT IOSObjectArray *OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_values();

FOUNDATION_EXPORT OrgGreenrobotGreendaoIdentityscopeIdentityScopeType *OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgGreenrobotGreendaoIdentityscopeIdentityScopeType *OrgGreenrobotGreendaoIdentityscopeIdentityScopeType_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoIdentityscopeIdentityScopeType)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoIdentityscopeIdentityScopeType")
