//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseDatabase")
#ifdef RESTRICT_OrgGreenrobotGreendaoDatabaseDatabase
#define INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseDatabase 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseDatabase 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoDatabaseDatabase

#if !defined (OrgGreenrobotGreendaoDatabaseDatabase_) && (INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseDatabase || defined(INCLUDE_OrgGreenrobotGreendaoDatabaseDatabase))
#define OrgGreenrobotGreendaoDatabaseDatabase_

@class IOSObjectArray;
@protocol AndroidDatabaseCursor;
@protocol OrgGreenrobotGreendaoDatabaseDatabaseStatement;

@protocol OrgGreenrobotGreendaoDatabaseDatabase < JavaObject >

- (id<AndroidDatabaseCursor>)rawQueryWithNSString:(NSString *)sql
                                withNSStringArray:(IOSObjectArray *)selectionArgs;

- (void)execSQLWithNSString:(NSString *)sql;

- (void)beginTransaction;

- (void)endTransaction;

- (jboolean)inTransaction;

- (void)setTransactionSuccessful;

- (void)execSQLWithNSString:(NSString *)sql
          withNSObjectArray:(IOSObjectArray *)bindArgs;

- (id<OrgGreenrobotGreendaoDatabaseDatabaseStatement>)compileStatementWithNSString:(NSString *)sql;

- (jboolean)isDbLockedByCurrentThread;

- (void)close;

- (id)getRawDatabase;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoDatabaseDatabase)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoDatabaseDatabase)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoDatabaseDatabase")
