//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_source.h"
#include "NetSqlcipherDatabaseSQLiteConstraintException.h"
#include "NetSqlcipherDatabaseSQLiteException.h"

@implementation NetSqlcipherDatabaseSQLiteConstraintException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  NetSqlcipherDatabaseSQLiteConstraintException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)error {
  NetSqlcipherDatabaseSQLiteConstraintException_initWithNSString_(self, error);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _NetSqlcipherDatabaseSQLiteConstraintException = { "SQLiteConstraintException", "net.sqlcipher.database", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_NetSqlcipherDatabaseSQLiteConstraintException;
}

@end

void NetSqlcipherDatabaseSQLiteConstraintException_init(NetSqlcipherDatabaseSQLiteConstraintException *self) {
  NetSqlcipherDatabaseSQLiteException_init(self);
}

NetSqlcipherDatabaseSQLiteConstraintException *new_NetSqlcipherDatabaseSQLiteConstraintException_init() {
  J2OBJC_NEW_IMPL(NetSqlcipherDatabaseSQLiteConstraintException, init)
}

NetSqlcipherDatabaseSQLiteConstraintException *create_NetSqlcipherDatabaseSQLiteConstraintException_init() {
  J2OBJC_CREATE_IMPL(NetSqlcipherDatabaseSQLiteConstraintException, init)
}

void NetSqlcipherDatabaseSQLiteConstraintException_initWithNSString_(NetSqlcipherDatabaseSQLiteConstraintException *self, NSString *error) {
  NetSqlcipherDatabaseSQLiteException_initWithNSString_(self, error);
}

NetSqlcipherDatabaseSQLiteConstraintException *new_NetSqlcipherDatabaseSQLiteConstraintException_initWithNSString_(NSString *error) {
  J2OBJC_NEW_IMPL(NetSqlcipherDatabaseSQLiteConstraintException, initWithNSString_, error)
}

NetSqlcipherDatabaseSQLiteConstraintException *create_NetSqlcipherDatabaseSQLiteConstraintException_initWithNSString_(NSString *error) {
  J2OBJC_CREATE_IMPL(NetSqlcipherDatabaseSQLiteConstraintException, initWithNSString_, error)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NetSqlcipherDatabaseSQLiteConstraintException)
