//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteCompiledSql")
#ifdef RESTRICT_NetSqlcipherDatabaseSQLiteCompiledSql
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteCompiledSql 0
#else
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteCompiledSql 1
#endif
#undef RESTRICT_NetSqlcipherDatabaseSQLiteCompiledSql

#if !defined (NetSqlcipherDatabaseSQLiteCompiledSql_) && (INCLUDE_ALL_NetSqlcipherDatabaseSQLiteCompiledSql || defined(INCLUDE_NetSqlcipherDatabaseSQLiteCompiledSql))
#define NetSqlcipherDatabaseSQLiteCompiledSql_

@class NetSqlcipherDatabaseSQLiteDatabase;

@interface NetSqlcipherDatabaseSQLiteCompiledSql : NSObject {
 @public
  NetSqlcipherDatabaseSQLiteDatabase *mDatabase_;
  jlong nHandle_;
  jlong nStatement_;
}

#pragma mark Protected

- (void)java_finalize;

#pragma mark Package-Private

- (instancetype)initWithNetSqlcipherDatabaseSQLiteDatabase:(NetSqlcipherDatabaseSQLiteDatabase *)db
                                              withNSString:(NSString *)sql;

- (jboolean)acquire;

- (void)release__;

- (void)releaseSqlStatement;

@end

J2OBJC_EMPTY_STATIC_INIT(NetSqlcipherDatabaseSQLiteCompiledSql)

J2OBJC_FIELD_SETTER(NetSqlcipherDatabaseSQLiteCompiledSql, mDatabase_, NetSqlcipherDatabaseSQLiteDatabase *)

FOUNDATION_EXPORT void NetSqlcipherDatabaseSQLiteCompiledSql_initWithNetSqlcipherDatabaseSQLiteDatabase_withNSString_(NetSqlcipherDatabaseSQLiteCompiledSql *self, NetSqlcipherDatabaseSQLiteDatabase *db, NSString *sql);

FOUNDATION_EXPORT NetSqlcipherDatabaseSQLiteCompiledSql *new_NetSqlcipherDatabaseSQLiteCompiledSql_initWithNetSqlcipherDatabaseSQLiteDatabase_withNSString_(NetSqlcipherDatabaseSQLiteDatabase *db, NSString *sql) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetSqlcipherDatabaseSQLiteCompiledSql *create_NetSqlcipherDatabaseSQLiteCompiledSql_initWithNetSqlcipherDatabaseSQLiteDatabase_withNSString_(NetSqlcipherDatabaseSQLiteDatabase *db, NSString *sql);

J2OBJC_TYPE_LITERAL_HEADER(NetSqlcipherDatabaseSQLiteCompiledSql)

#endif

#pragma pop_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteCompiledSql")
