//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteClosable")
#ifdef RESTRICT_NetSqlcipherDatabaseSQLiteClosable
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteClosable 0
#else
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteClosable 1
#endif
#undef RESTRICT_NetSqlcipherDatabaseSQLiteClosable

#if !defined (NetSqlcipherDatabaseSQLiteClosable_) && (INCLUDE_ALL_NetSqlcipherDatabaseSQLiteClosable || defined(INCLUDE_NetSqlcipherDatabaseSQLiteClosable))
#define NetSqlcipherDatabaseSQLiteClosable_

@interface NetSqlcipherDatabaseSQLiteClosable : NSObject

#pragma mark Public

- (instancetype)init;

- (void)acquireReference;

- (void)releaseReference;

- (void)releaseReferenceFromContainer;

#pragma mark Protected

- (void)onAllReferencesReleased;

- (void)onAllReferencesReleasedFromContainer;

@end

J2OBJC_EMPTY_STATIC_INIT(NetSqlcipherDatabaseSQLiteClosable)

FOUNDATION_EXPORT void NetSqlcipherDatabaseSQLiteClosable_init(NetSqlcipherDatabaseSQLiteClosable *self);

J2OBJC_TYPE_LITERAL_HEADER(NetSqlcipherDatabaseSQLiteClosable)

#endif

#pragma pop_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteClosable")
