//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteDatabaseHook")
#ifdef RESTRICT_NetSqlcipherDatabaseSQLiteDatabaseHook
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteDatabaseHook 0
#else
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteDatabaseHook 1
#endif
#undef RESTRICT_NetSqlcipherDatabaseSQLiteDatabaseHook

#if !defined (NetSqlcipherDatabaseSQLiteDatabaseHook_) && (INCLUDE_ALL_NetSqlcipherDatabaseSQLiteDatabaseHook || defined(INCLUDE_NetSqlcipherDatabaseSQLiteDatabaseHook))
#define NetSqlcipherDatabaseSQLiteDatabaseHook_

@class NetSqlcipherDatabaseSQLiteDatabase;

@protocol NetSqlcipherDatabaseSQLiteDatabaseHook < JavaObject >

- (void)preKeyWithNetSqlcipherDatabaseSQLiteDatabase:(NetSqlcipherDatabaseSQLiteDatabase *)database;

- (void)postKeyWithNetSqlcipherDatabaseSQLiteDatabase:(NetSqlcipherDatabaseSQLiteDatabase *)database;

@end

J2OBJC_EMPTY_STATIC_INIT(NetSqlcipherDatabaseSQLiteDatabaseHook)

J2OBJC_TYPE_LITERAL_HEADER(NetSqlcipherDatabaseSQLiteDatabaseHook)

#endif

#pragma pop_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteDatabaseHook")
