//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetSqlcipherDatabaseSqliteWrapper")
#ifdef RESTRICT_NetSqlcipherDatabaseSqliteWrapper
#define INCLUDE_ALL_NetSqlcipherDatabaseSqliteWrapper 0
#else
#define INCLUDE_ALL_NetSqlcipherDatabaseSqliteWrapper 1
#endif
#undef RESTRICT_NetSqlcipherDatabaseSqliteWrapper

#if !defined (NetSqlcipherDatabaseSqliteWrapper_) && (INCLUDE_ALL_NetSqlcipherDatabaseSqliteWrapper || defined(INCLUDE_NetSqlcipherDatabaseSqliteWrapper))
#define NetSqlcipherDatabaseSqliteWrapper_

@class AndroidContentContext;
@class NetSqlcipherDatabaseSQLiteException;
@protocol AndroidDatabaseCursor;

@interface NetSqlcipherDatabaseSqliteWrapper : NSObject

#pragma mark Public

+ (void)checkSQLiteExceptionWithAndroidContentContext:(AndroidContentContext *)context
              withNetSqlcipherDatabaseSQLiteException:(NetSqlcipherDatabaseSQLiteException *)e;

+ (jboolean)requeryWithAndroidContentContext:(AndroidContentContext *)context
                   withAndroidDatabaseCursor:(id<AndroidDatabaseCursor>)cursor;

@end

J2OBJC_EMPTY_STATIC_INIT(NetSqlcipherDatabaseSqliteWrapper)

FOUNDATION_EXPORT void NetSqlcipherDatabaseSqliteWrapper_checkSQLiteExceptionWithAndroidContentContext_withNetSqlcipherDatabaseSQLiteException_(AndroidContentContext *context, NetSqlcipherDatabaseSQLiteException *e);

FOUNDATION_EXPORT jboolean NetSqlcipherDatabaseSqliteWrapper_requeryWithAndroidContentContext_withAndroidDatabaseCursor_(AndroidContentContext *context, id<AndroidDatabaseCursor> cursor);

J2OBJC_TYPE_LITERAL_HEADER(NetSqlcipherDatabaseSqliteWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_NetSqlcipherDatabaseSqliteWrapper")
