//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteStatement")
#ifdef RESTRICT_NetSqlcipherDatabaseSQLiteStatement
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteStatement 0
#else
#define INCLUDE_ALL_NetSqlcipherDatabaseSQLiteStatement 1
#endif
#undef RESTRICT_NetSqlcipherDatabaseSQLiteStatement

#if !defined (NetSqlcipherDatabaseSQLiteStatement_) && (INCLUDE_ALL_NetSqlcipherDatabaseSQLiteStatement || defined(INCLUDE_NetSqlcipherDatabaseSQLiteStatement))
#define NetSqlcipherDatabaseSQLiteStatement_

#define RESTRICT_NetSqlcipherDatabaseSQLiteProgram 1
#define INCLUDE_NetSqlcipherDatabaseSQLiteProgram 1
#include "NetSqlcipherDatabaseSQLiteProgram.h"

@class NetSqlcipherDatabaseSQLiteDatabase;

@interface NetSqlcipherDatabaseSQLiteStatement : NetSqlcipherDatabaseSQLiteProgram

#pragma mark Public

- (void)execute;

- (jlong)executeInsert;

- (jint)executeUpdateDelete;

- (jlong)simpleQueryForLong;

- (NSString *)simpleQueryForString;

#pragma mark Package-Private

- (instancetype)initWithNetSqlcipherDatabaseSQLiteDatabase:(NetSqlcipherDatabaseSQLiteDatabase *)db
                                              withNSString:(NSString *)sql;

@end

J2OBJC_EMPTY_STATIC_INIT(NetSqlcipherDatabaseSQLiteStatement)

FOUNDATION_EXPORT void NetSqlcipherDatabaseSQLiteStatement_initWithNetSqlcipherDatabaseSQLiteDatabase_withNSString_(NetSqlcipherDatabaseSQLiteStatement *self, NetSqlcipherDatabaseSQLiteDatabase *db, NSString *sql);

FOUNDATION_EXPORT NetSqlcipherDatabaseSQLiteStatement *new_NetSqlcipherDatabaseSQLiteStatement_initWithNetSqlcipherDatabaseSQLiteDatabase_withNSString_(NetSqlcipherDatabaseSQLiteDatabase *db, NSString *sql) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetSqlcipherDatabaseSQLiteStatement *create_NetSqlcipherDatabaseSQLiteStatement_initWithNetSqlcipherDatabaseSQLiteDatabase_withNSString_(NetSqlcipherDatabaseSQLiteDatabase *db, NSString *sql);

J2OBJC_TYPE_LITERAL_HEADER(NetSqlcipherDatabaseSQLiteStatement)

#endif

#pragma pop_macro("INCLUDE_ALL_NetSqlcipherDatabaseSQLiteStatement")
