//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OrgGreenrobotGreendaoAnnotationEntity.h"
#include "OrgGreenrobotGreendaoAnnotationIndex.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@interface OrgGreenrobotGreendaoAnnotationEntity : NSObject

@end

__attribute__((unused)) static IOSObjectArray *OrgGreenrobotGreendaoAnnotationEntity__Annotations$0();

@implementation OrgGreenrobotGreendaoAnnotationEntity

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LOrgGreenrobotGreendaoAnnotationIndex;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(nameInDb);
  methods[1].selector = @selector(indexes);
  methods[2].selector = @selector(createInDb);
  methods[3].selector = @selector(schema);
  methods[4].selector = @selector(active);
  methods[5].selector = @selector(generateConstructors);
  methods[6].selector = @selector(generateGettersSetters);
  methods[7].selector = @selector(protobuf);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&OrgGreenrobotGreendaoAnnotationEntity__Annotations$0 };
  static const J2ObjcClassInfo _OrgGreenrobotGreendaoAnnotationEntity = { "Entity", "org.greenrobot.greendao.annotation", ptrTable, methods, NULL, 7, 0x2609, 8, 0, -1, -1, -1, -1, 0 };
  return &_OrgGreenrobotGreendaoAnnotationEntity;
}

@end

IOSObjectArray *OrgGreenrobotGreendaoAnnotationEntity__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, SOURCE)), create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, TYPE) } count:1 type:JavaLangAnnotationElementType_class_()]) } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgGreenrobotGreendaoAnnotationEntity)
