//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationApihintBeta")
#ifdef RESTRICT_OrgGreenrobotGreendaoAnnotationApihintBeta
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationApihintBeta 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationApihintBeta 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoAnnotationApihintBeta

#if !defined (OrgGreenrobotGreendaoAnnotationApihintBeta_) && (INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationApihintBeta || defined(INCLUDE_OrgGreenrobotGreendaoAnnotationApihintBeta))
#define OrgGreenrobotGreendaoAnnotationApihintBeta_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol OrgGreenrobotGreendaoAnnotationApihintBeta < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoAnnotationApihintBeta)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoAnnotationApihintBeta)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationApihintBeta")
