//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationConvert")
#ifdef RESTRICT_OrgGreenrobotGreendaoAnnotationConvert
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationConvert 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationConvert 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoAnnotationConvert

#if !defined (OrgGreenrobotGreendaoAnnotationConvert_) && (INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationConvert || defined(INCLUDE_OrgGreenrobotGreendaoAnnotationConvert))
#define OrgGreenrobotGreendaoAnnotationConvert_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol OrgGreenrobotGreendaoAnnotationConvert < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoAnnotationConvert)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoAnnotationConvert)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationConvert")
