//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComSquareupSqldelightInternalSqliteLiterals")
#ifdef RESTRICT_ComSquareupSqldelightInternalSqliteLiterals
#define INCLUDE_ALL_ComSquareupSqldelightInternalSqliteLiterals 0
#else
#define INCLUDE_ALL_ComSquareupSqldelightInternalSqliteLiterals 1
#endif
#undef RESTRICT_ComSquareupSqldelightInternalSqliteLiterals

#if !defined (ComSquareupSqldelightInternalSqliteLiterals_) && (INCLUDE_ALL_ComSquareupSqldelightInternalSqliteLiterals || defined(INCLUDE_ComSquareupSqldelightInternalSqliteLiterals))
#define ComSquareupSqldelightInternalSqliteLiterals_

@class IOSByteArray;

@interface ComSquareupSqldelightInternalSqliteLiterals : NSObject

#pragma mark Public

+ (NSString *)forBlobWithByteArray:(IOSByteArray *)bytes;

@end

J2OBJC_STATIC_INIT(ComSquareupSqldelightInternalSqliteLiterals)

FOUNDATION_EXPORT NSString *ComSquareupSqldelightInternalSqliteLiterals_forBlobWithByteArray_(IOSByteArray *bytes);

J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSqldelightInternalSqliteLiterals)

#endif

#pragma pop_macro("INCLUDE_ALL_ComSquareupSqldelightInternalSqliteLiterals")
