//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationGenerated")
#ifdef RESTRICT_OrgGreenrobotGreendaoAnnotationGenerated
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationGenerated 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationGenerated 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoAnnotationGenerated

#if !defined (OrgGreenrobotGreendaoAnnotationGenerated_) && (INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationGenerated || defined(INCLUDE_OrgGreenrobotGreendaoAnnotationGenerated))
#define OrgGreenrobotGreendaoAnnotationGenerated_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol OrgGreenrobotGreendaoAnnotationGenerated < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoAnnotationGenerated)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoAnnotationGenerated)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationGenerated")
