//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationId")
#ifdef RESTRICT_OrgGreenrobotGreendaoAnnotationId
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationId 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationId 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoAnnotationId

#if !defined (OrgGreenrobotGreendaoAnnotationId_) && (INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationId || defined(INCLUDE_OrgGreenrobotGreendaoAnnotationId))
#define OrgGreenrobotGreendaoAnnotationId_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol OrgGreenrobotGreendaoAnnotationId < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoAnnotationId)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoAnnotationId)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationId")
