//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationOrderBy")
#ifdef RESTRICT_OrgGreenrobotGreendaoAnnotationOrderBy
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationOrderBy 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationOrderBy 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoAnnotationOrderBy

#if !defined (OrgGreenrobotGreendaoAnnotationOrderBy_) && (INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationOrderBy || defined(INCLUDE_OrgGreenrobotGreendaoAnnotationOrderBy))
#define OrgGreenrobotGreendaoAnnotationOrderBy_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol OrgGreenrobotGreendaoAnnotationOrderBy < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoAnnotationOrderBy)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoAnnotationOrderBy)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationOrderBy")
