//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OrgGreenrobotGreendaoAnnotationJoinProperty.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@interface OrgGreenrobotGreendaoAnnotationJoinProperty : NSObject

@end

__attribute__((unused)) static IOSObjectArray *OrgGreenrobotGreendaoAnnotationJoinProperty__Annotations$0();

@implementation OrgGreenrobotGreendaoAnnotationJoinProperty

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(name);
  methods[1].selector = @selector(referencedName);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&OrgGreenrobotGreendaoAnnotationJoinProperty__Annotations$0 };
  static const J2ObjcClassInfo _OrgGreenrobotGreendaoAnnotationJoinProperty = { "JoinProperty", "org.greenrobot.greendao.annotation", ptrTable, methods, NULL, 7, 0x2609, 2, 0, -1, -1, -1, -1, 0 };
  return &_OrgGreenrobotGreendaoAnnotationJoinProperty;
}

@end

IOSObjectArray *OrgGreenrobotGreendaoAnnotationJoinProperty__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, SOURCE)), create_JavaLangAnnotationTarget([IOSObjectArray arrayWithLength:0 type:JavaLangAnnotationElementType_class_()]) } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgGreenrobotGreendaoAnnotationJoinProperty)
