//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationToOne")
#ifdef RESTRICT_OrgGreenrobotGreendaoAnnotationToOne
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationToOne 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationToOne 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoAnnotationToOne

#if !defined (OrgGreenrobotGreendaoAnnotationToOne_) && (INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationToOne || defined(INCLUDE_OrgGreenrobotGreendaoAnnotationToOne))
#define OrgGreenrobotGreendaoAnnotationToOne_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol OrgGreenrobotGreendaoAnnotationToOne < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoAnnotationToOne)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoAnnotationToOne)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoAnnotationToOne")
