//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgGreenrobotGreendaoConverterPropertyConverter")
#ifdef RESTRICT_OrgGreenrobotGreendaoConverterPropertyConverter
#define INCLUDE_ALL_OrgGreenrobotGreendaoConverterPropertyConverter 0
#else
#define INCLUDE_ALL_OrgGreenrobotGreendaoConverterPropertyConverter 1
#endif
#undef RESTRICT_OrgGreenrobotGreendaoConverterPropertyConverter

#if !defined (OrgGreenrobotGreendaoConverterPropertyConverter_) && (INCLUDE_ALL_OrgGreenrobotGreendaoConverterPropertyConverter || defined(INCLUDE_OrgGreenrobotGreendaoConverterPropertyConverter))
#define OrgGreenrobotGreendaoConverterPropertyConverter_

@protocol OrgGreenrobotGreendaoConverterPropertyConverter < JavaObject >

- (id)convertToEntityPropertyWithId:(id)databaseValue;

- (id)convertToDatabaseValueWithId:(id)entityProperty;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGreenrobotGreendaoConverterPropertyConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgGreenrobotGreendaoConverterPropertyConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgGreenrobotGreendaoConverterPropertyConverter")
